using System;

namespace ZeroGraphics.Imaging.Gpu.Shaders
{
    /// <summary>
    /// Precompiled Direct3D 11 DirectCompute HLSL Shader Bytecodes (Shader Model 5.0).
    /// Embedded as Base64 strings to eliminate runtime shader compiler dependencies.
    /// Features Local Data Share (groupshared LDS) caching for ultra-high memory bandwidth efficiency.
    /// </summary>
    public static class ComputeShaderBytecodes
    {
        /// <summary>
        /// CS 5.0 Color Transformation, Brightness, Contrast, Gamma and Threshold.
        /// </summary>
        public static byte[] CsColorAdjustBytecode { get; } = Convert.FromBase64String(
            "RFhCQ1GGvhsAYN78nxKE0h+BTo0BAAAAKAgAAAUAAAA0AAAA9AIAAAQDAAAUAwAAjAcAAFJERUa4AgAA" +
            "AQAAAMgAAAADAAAAPAAAAAAFU0MAgQAAkAIAAFJEMTE8AAAAGAAAACAAAAAoAAAAJAAAAAwAAAAAAAAA" +
            "nAAAAAIAAAAFAAAABAAAAP////8AAAAAAQAAAA0AAACnAAAABAAAAAUAAAAEAAAA/////wAAAAABAAAA" +
            "DQAAALMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAABAAAAQ29sb3JJbnB1dABDb2xvck91dHB1dABD" +
            "b2xvckNvbXB1dGVCdWZmZXIAq6uzAAAABwAAAOAAAAAgAAAAAAAAAAAAAAD4AQAAAAAAAAQAAAACAAAA" +
            "DAIAAAAAAAD/////AAAAAP////8AAAAAMAIAAAQAAAAEAAAAAgAAAAwCAAAAAAAA/////wAAAAD/////" +
            "AAAAADkCAAAIAAAABAAAAAIAAAAMAgAAAAAAAP////8AAAAA/////wAAAABDAgAADAAAAAQAAAACAAAA" +
            "DAIAAAAAAAD/////AAAAAP////8AAAAASgIAABAAAAAEAAAAAgAAAAwCAAAAAAAA/////wAAAAD/////" +
            "AAAAAFACAAAUAAAABAAAAAIAAAAMAgAAAAAAAP////8AAAAA/////wAAAABaAgAAGAAAAAgAAAAAAAAA" +
            "bAIAAAAAAAD/////AAAAAP////8AAAAAQnJpZ2h0bmVzcwBmbG9hdACrq6sAAAMAAQABAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAMCAABDb250cmFzdABHcmF5c2NhbGUASW52ZXJ0AEdhbW1hAFRocmVzaG9s" +
            "ZABQYWRkaW5nAGZsb2F0MgCrq6sBAAMAAQACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGICAABNaWNy" +
            "b3NvZnQgKFIpIEhMU0wgU2hhZGVyIENvbXBpbGVyIDEwLjEASVNHTggAAAAAAAAACAAAAE9TR04IAAAA" +
            "AAAAAAgAAABTSEVYcAQAAFAABQAcAQAAaggAAVkAAARGjiAAAAAAAAIAAABYGAAEAHAQAAAAAABVVQAA" +
            "nBgABADgEQAAAAAAVVUAAF8AAAIyAAIAaAAAAgMAAACbAAAEEAAAABAAAAABAAAAPRAAicIAAIBDVRUA" +
            "MgAQAAAAAAABQAAAAAAAAEbuEQAAAAAAUAAABjIAEAAAAAAARgACAEYAEAAAAAAAPAAABxIAEAAAAAAA" +
            "GgAQAAAAAAAKABAAAAAAAB8ABAMKABAAAAAAAD4AAAEVAAABNgAABDIAEAAAAAAARgACADYAAAjCABAA" +
            "AAAAAAJAAAAAAAAAAAAAAAAAAAAAAAAALQAAicIAAIBDVRUA8gAQAAAAAABGDhAAAAAAAEZ+EAAAAAAA" +
            "MQAACzIAEAABAAAAAkAAAAAAAD8AAAA/AAAAAAAAAADmiiAAAAAAAAAAAAAQAAAKQgAQAAEAAABGAhAA" +
            "AAAAAAJAAADQs1k+WRc3P5jdkz0AAAAANwAACdIAEAABAAAABgAQAAEAAACmChAAAQAAAAYJEAAAAAAA" +
            "AAAACtIAEAABAAAABg4QAAEAAAACQAAAAAAAvwAAAAAAAAC/AAAAvzIAAAvSABAAAQAAAAYOEAABAAAA" +
            "VoUgAAAAAAAAAAAABoAgAAAAAAAAAAAAAAAACtIAEAABAAAABg4QAAEAAAACQAAAAAAAPwAAAAAAAAA/" +
            "AAAAPwAAAAtyABAAAgAAAIYDEIBBAAAAAQAAAAJAAAAAAIA/AACAPwAAgD8AAAAANwAACXIAEAABAAAA" +
            "VgUQAAEAAABGAhAAAgAAAIYDEAABAAAAMQAACIIAEAABAAAAAUAAAArXIzwKgCAAAAAAAAEAAAAAAAAI" +
            "EgAQAAIAAAAKgCAAAAAAAAEAAAABQAAAAACAvzEAAAgSABAAAgAAAAFAAABvEoM6CgAQgIEAAAACAAAA" +
            "AQAAB4IAEAABAAAAOgAQAAEAAAAKABAAAgAAADQAAApyABAAAgAAAEYCEAABAAAAAkAAAKzFJzesxSc3" +
            "rMUnNwAAAAAOAAALggAQAAIAAAACQAAAAACAPwAAgD8AAIA/AACAPwqAIAAAAAAAAQAAAC8AAAVyABAA" +
            "AgAAAEYCEAACAAAAOAAAB3IAEAACAAAARgIQAAIAAAD2DxAAAgAAABkAAAVyABAAAgAAAEYCEAACAAAA" +
            "NwAACXIAEAABAAAA9g8QAAEAAABGAhAAAgAAAEYCEAABAAAAHQAACIIAEAABAAAAGoAgAAAAAAABAAAA" +
            "AUAAAAAAAAAQAAAKEgAQAAIAAABGAhAAAQAAAAJAAADQs1k+WRc3P5jdkz0AAAAAHQAACBIAEAACAAAA" +
            "CgAQAAIAAAAagCAAAAAAAAEAAAABAAAHEgAQAAIAAAAKABAAAgAAAAFAAAAAAIA/NyAACXIAEAAAAAAA" +
            "9g8QAAEAAAAGABAAAgAAAEYCEAABAAAANiAABYIAEAAAAAAAOgAQAAAAAACkAAAG8uARAAAAAABGBQIA" +
            "Rg4QAAAAAAA+AAABU1RBVJQAAAAjAAAAAwAAAAAAAAABAAAAEQAAAAAAAAAEAAAAAgAAAAEAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAwAAAAQAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAA"
        );

        /// <summary>
        /// CS 5.0 Separable 1D Gaussian Blur (Horizontal pass using 128-thread groupshared LDS apron).
        /// </summary>
        public static byte[] CsBlurHorizontalBytecode { get; } = Convert.FromBase64String(
            "RFhCQy3lV9GPfdpV+h+e2VNr2NcBAAAAiA0AAAUAAAA0AAAA7AIAAPwCAAAMAwAA7AwAAFJERUawAgAA" +
            "AQAAAMAAAAADAAAAPAAAAAAFU0MAgQAAiAIAAFJEMTE8AAAAGAAAACAAAAAoAAAAJAAAAAwAAAAAAAAA" +
            "nAAAAAIAAAAFAAAABAAAAP////8AAAAAAQAAAA0AAACnAAAABAAAAAUAAAAEAAAA/////wAAAAABAAAA" +
            "DQAAALMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAABAAAAQmx1cklucHV0SABCbHVyT3V0cHV0SABC" +
            "bHVyUGFyYW1zSACrswAAAAUAAADYAAAAMAAAAAAAAAAAAAAAoAEAAAAAAAAEAAAAAgAAALQBAAAAAAAA" +
            "/////wAAAAD/////AAAAANgBAAAEAAAABAAAAAIAAAC0AQAAAAAAAP////8AAAAA/////wAAAADlAQAA" +
            "CAAAAAQAAAACAAAA+AEAAAAAAAD/////AAAAAP////8AAAAAHAIAAAwAAAAEAAAAAAAAACwCAAAAAAAA" +
            "/////wAAAAD/////AAAAAFACAAAQAAAAIAAAAAIAAABkAgAAAAAAAP////8AAAAA/////wAAAABJbWFn" +
            "ZVdpZHRoSABkd29yZACrqwAAEwABAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAArAEAAEltYWdlSGVp" +
            "Z2h0SABCbHVyUmFkaXVzSABpbnQAq6urAAACAAEAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADxAQAA" +
            "Qmx1clBhZEgAZmxvYXQAqwAAAwABAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJQIAAEJsdXJXZWln" +
            "aHRzSABmbG9hdDQAAQADAAEABAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABdAgAATWljcm9zb2Z0IChS" +
            "KSBITFNMIFNoYWRlciBDb21waWxlciAxMC4xAElTR04IAAAAAAAAAAgAAABPU0dOCAAAAAAAAAAIAAAA" +
            "U0hFWNgJAABQAAUAdgIAAGoIAAFZAAAERo4gAAAAAAADAAAAWBgABABwEAAAAAAAVVUAAJwYAAQA4BEA" +
            "AAAAAFVVAABfAAACMhACAF8AAAISIAIAaAAAAgYAAACgAAAFAPARAAAAAAAQAAAAjgAAAJsAAASAAAAA" +
            "AQAAAAEAAAAhAAAHEgAQAAAAAAAaEAIAGoAgAAAAAAAAAAAAHwAEAwoAEAAAAAAAPgAAARUAAAEkAAAI" +
            "EgAQAAAAAAAqgCAAAAAAAAAAAAABQAAAAQAAACUAAAcSABAAAAAAAAoAEAAAAAAAAUAAAAcAAAAjAAAH" +
            "EgAQAAEAAAAKEAIAAUAAAIAAAAAKIAIAHgAABiIAEAAAAAAACgAQAAAAAAAKIAIAHgAACEIAEAAAAAAA" +
            "CoAgAAAAAAAAAAAAAUAAAP////8lAAAHIgAQAAIAAAAqABAAAAAAAAoAEAABAAAANgAABEIAEAACAAAA" +
            "GhACADYAAAWCABAAAgAAAAFAAAAAAAAALQAAicIAAIBDVRUA8gAQAAMAAACWDxAAAgAAAEZ+EAAAAAAA" +
            "qAAACfLwEQAAAAAAGgAQAAAAAAABQAAAAAAAAEYOEAADAAAAIgAABoIAEAAAAAAACiACAAoAEAAAAAAA" +
            "HwAEAzoAEAAAAAAAKQAABoIAEAAAAAAAChACAAFAAAAHAAAAHgAACCIAEAACAAAACgAQgEEAAAAAAAAA" +
            "OgAQAAAAAAAeAAAGIgAQAAIAAAAaABAAAgAAAAogAgAkAAAHIgAQAAIAAAAaABAAAgAAAAFAAAAAAAAA" +
            "JQAABxIAEAACAAAAKgAQAAAAAAAaABAAAgAAAC0AAInCAACAQ1UVAPIAEAADAAAAhg8QAAIAAABGfhAA" +
            "AAAAAKgAAAjy8BEAAAAAAAogAgABQAAAAAAAAEYOEAADAAAAHgAAB4IAEAAAAAAAOgAQAAAAAAABQAAA" +
            "gAAAAB4AAAaCABAAAAAAADoAEAAAAAAACiACAB4AAAcSABAAAgAAAAoAEAAAAAAAAUAAAIAAAAAeAAAG" +
            "EgAQAAIAAAAKABAAAgAAAAogAgAlAAAHEgAQAAMAAAAqABAAAAAAADoAEAAAAAAANgAABeIAEAADAAAA" +
            "pg8QAAIAAAAtAACJwgAAgENVFQDyABAAAwAAAEYOEAADAAAARn4QAAAAAACoAAAJ8vARAAAAAAAKABAA" +
            "AgAAAAFAAAAAAAAARg4QAAMAAAAVAAABvhgAASIAAAhCABAAAAAAAAoAEAABAAAACoAgAAAAAAAAAAAA" +
            "HwAEAyoAEAAAAAAApwAACfIAEAACAAAAGgAQAAAAAAABQAAAAAAAAEb+EQAAAAAAHgAACsIAEAAAAAAA" +
            "VgUQAAAAAAACQAAAAAAAAAAAAAD/////AQAAAKcAAAnyABAAAwAAACoAEAAAAAAAAUAAAAAAAABG/hEA" +
            "AAAAAKcAAAnyABAABAAAADoAEAAAAAAAAUAAAAAAAABG/hEAAAAAAAAAAAfyABAAAwAAAEYOEAADAAAA" +
            "Rg4QAAQAAAA4AAAI8gAQAAMAAABGDhAAAwAAAFaFIAAAAAAAAQAAADIAAAryABAAAgAAAEYOEAACAAAA" +
            "BoAgAAAAAAABAAAARg4QAAMAAAAhAAAK8gAQAAMAAAAGABAAAAAAAAJAAAACAAAAAwAAAAQAAAAFAAAA" +
            "HwAEAwoAEAADAAAAHgAACsIAEAAAAAAAVgUQAAAAAAACQAAAAAAAAAAAAAD+////AgAAAKcAAAnyABAA" +
            "BAAAACoAEAAAAAAAAUAAAAAAAABG/hEAAAAAAKcAAAnyABAABQAAADoAEAAAAAAAAUAAAAAAAABG/hEA" +
            "AAAAAAAAAAfyABAABAAAAEYOEAAEAAAARg4QAAUAAAAyAAAK8gAQAAIAAABGDhAABAAAAKaKIAAAAAAA" +
            "AQAAAEYOEAACAAAAFQAAAR8ABAMaABAAAwAAAB4AAArCABAAAAAAAFYFEAAAAAAAAkAAAAAAAAAAAAAA" +
            "/f///wMAAACnAAAJ8gAQAAQAAAAqABAAAAAAAAFAAAAAAAAARv4RAAAAAACnAAAJ8gAQAAUAAAA6ABAA" +
            "AAAAAAFAAAAAAAAARv4RAAAAAAAAAAAH8gAQAAQAAABGDhAABAAAAEYOEAAFAAAAMgAACvIAEAACAAAA" +
            "Rg4QAAQAAAD2jyAAAAAAAAEAAABGDhAAAgAAABUAAAEfAAQDKgAQAAMAAAAeAAAKwgAQAAAAAABWBRAA" +
            "AAAAAAJAAAAAAAAAAAAAAPz///8EAAAApwAACfIAEAAEAAAAKgAQAAAAAAABQAAAAAAAAEb+EQAAAAAA" +
            "pwAACfIAEAAFAAAAOgAQAAAAAAABQAAAAAAAAEb+EQAAAAAAAAAAB/IAEAAEAAAARg4QAAQAAABGDhAA" +
            "BQAAADIAAAryABAAAgAAAEYOEAAEAAAABoAgAAAAAAACAAAARg4QAAIAAAAVAAABHwAEAzoAEAADAAAA" +
            "HgAACsIAEAAAAAAAVgUQAAAAAAACQAAAAAAAAAAAAAD7////BQAAAKcAAAnyABAAAwAAACoAEAAAAAAA" +
            "AUAAAAAAAABG/hEAAAAAAKcAAAnyABAABAAAADoAEAAAAAAAAUAAAAAAAABG/hEAAAAAAAAAAAfyABAA" +
            "AwAAAEYOEAADAAAARg4QAAQAAAAyAAAK8gAQAAIAAABGDhAAAwAAAFaFIAAAAAAAAgAAAEYOEAACAAAA" +
            "FQAAASEAAApSABAAAAAAAAYAEAAAAAAAAkAAAAYAAAAAAAAABwAAAAAAAAAfAAQDCgAQAAAAAAAeAAAK" +
            "kgAQAAAAAABWBRAAAAAAAAJAAAD6////AAAAAAAAAAAGAAAApwAACfIAEAADAAAACgAQAAAAAAABQAAA" +
            "AAAAAEb+EQAAAAAApwAACfIAEAAEAAAAOgAQAAAAAAABQAAAAAAAAEb+EQAAAAAAAAAAB/IAEAADAAAA" +
            "Rg4QAAMAAABGDhAABAAAADIAAAryABAAAgAAAEYOEAADAAAApoogAAAAAAACAAAARg4QAAIAAAAVAAAB" +
            "HwAEAyoAEAAAAAAAHgAACjIAEAAAAAAAVgUQAAAAAAACQAAA+f///wcAAAAAAAAAAAAAAKcAAAnyABAA" +
            "AwAAAAoAEAAAAAAAAUAAAAAAAABG/hEAAAAAAKcAAAnyABAAAAAAABoAEAAAAAAAAUAAAAAAAABG/hEA" +
            "AAAAAAAAAAfyABAAAAAAAEYOEAAAAAAARg4QAAMAAAAyAAAK8gAQAAIAAABGDhAAAAAAAPaPIAAAAAAA" +
            "AgAAAEYOEAACAAAAFQAAATYAAATiABAAAQAAAFYVAgCkAAAH8uARAAAAAABGDhAAAQAAAEYOEAACAAAA" +
            "FQAAAT4AAAFTVEFUlAAAAFoAAAAGAAAAAAAAAAIAAAAPAAAAHAAAAAAAAAACAAAACQAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAMAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAEAAAA="
        );

        /// <summary>
        /// CS 5.0 Separable 1D Gaussian Blur (Vertical pass using 128-thread groupshared LDS apron).
        /// </summary>
        public static byte[] CsBlurVerticalBytecode { get; } = Convert.FromBase64String(
            "RFhCQ5gpRemqFM7nhjJB8bgfrnsBAAAAlA0AAAUAAAA0AAAA7AIAAPwCAAAMAwAA+AwAAFJERUawAgAA" +
            "AQAAAMAAAAADAAAAPAAAAAAFU0MAgQAAiAIAAFJEMTE8AAAAGAAAACAAAAAoAAAAJAAAAAwAAAAAAAAA" +
            "nAAAAAIAAAAFAAAABAAAAP////8AAAAAAQAAAA0AAACnAAAABAAAAAUAAAAEAAAA/////wAAAAABAAAA" +
            "DQAAALMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAABAAAAQmx1cklucHV0VgBCbHVyT3V0cHV0VgBC" +
            "bHVyUGFyYW1zVgCrswAAAAUAAADYAAAAMAAAAAAAAAAAAAAAoAEAAAAAAAAEAAAAAgAAALQBAAAAAAAA" +
            "/////wAAAAD/////AAAAANgBAAAEAAAABAAAAAIAAAC0AQAAAAAAAP////8AAAAA/////wAAAADlAQAA" +
            "CAAAAAQAAAACAAAA+AEAAAAAAAD/////AAAAAP////8AAAAAHAIAAAwAAAAEAAAAAAAAACwCAAAAAAAA" +
            "/////wAAAAD/////AAAAAFACAAAQAAAAIAAAAAIAAABkAgAAAAAAAP////8AAAAA/////wAAAABJbWFn" +
            "ZVdpZHRoVgBkd29yZACrqwAAEwABAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAArAEAAEltYWdlSGVp" +
            "Z2h0VgBCbHVyUmFkaXVzVgBpbnQAq6urAAACAAEAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADxAQAA" +
            "Qmx1clBhZFYAZmxvYXQAqwAAAwABAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJQIAAEJsdXJXZWln" +
            "aHRzVgBmbG9hdDQAAQADAAEABAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABdAgAATWljcm9zb2Z0IChS" +
            "KSBITFNMIFNoYWRlciBDb21waWxlciAxMC4xAElTR04IAAAAAAAAAAgAAABPU0dOCAAAAAAAAAAIAAAA" +
            "U0hFWOQJAABQAAUAeQIAAGoIAAFZAAAERo4gAAAAAAADAAAAWBgABABwEAAAAAAAVVUAAJwYAAQA4BEA" +
            "AAAAAFVVAABfAAACMhACAF8AAAIiIAIAaAAAAgYAAACgAAAFAPARAAAAAAAQAAAAjgAAAJsAAAQBAAAA" +
            "gAAAAAEAAAAhAAAHEgAQAAAAAAAKEAIACoAgAAAAAAAAAAAAHwAEAwoAEAAAAAAAPgAAARUAAAEkAAAI" +
            "EgAQAAAAAAAqgCAAAAAAAAAAAAABQAAAAQAAACUAAAcSABAAAAAAAAoAEAAAAAAAAUAAAAcAAAAjAAAK" +
            "4gAQAAEAAABWFQIAAkAAAAAAAACAAAAAgAAAAIAAAABWJQIAHgAABiIAEAAAAAAACgAQAAAAAAAaIAIA" +
            "HgAACEIAEAAAAAAAGoAgAAAAAAAAAAAAAUAAAP////8lAAAHEgAQAAIAAAAqABAAAAAAADoAEAABAAAA" +
            "NgAABCIAEAACAAAAChACADYAAAVCABAAAgAAAAFAAAAAAAAALQAAicIAAIBDVRUA8gAQAAMAAAAWChAA" +
            "AgAAAEZ+EAAAAAAAqAAACfLwEQAAAAAAGgAQAAAAAAABQAAAAAAAAEYOEAADAAAAIgAABoIAEAAAAAAA" +
            "GiACAAoAEAAAAAAAHwAEAzoAEAAAAAAAKQAABoIAEAAAAAAAGhACAAFAAAAHAAAAHgAACBIAEAACAAAA" +
            "CgAQgEEAAAAAAAAAOgAQAAAAAAAeAAAGEgAQAAIAAAAKABAAAgAAABogAgAkAAAHEgAQAAIAAAAKABAA" +
            "AgAAAAFAAAAAAAAAJQAAB4IAEAACAAAAKgAQAAAAAAAKABAAAgAAAC0AAInCAACAQ1UVAPIAEAADAAAA" +
            "1goQAAIAAABGfhAAAAAAAKgAAAjy8BEAAAAAABogAgABQAAAAAAAAEYOEAADAAAAHgAAB4IAEAAAAAAA" +
            "OgAQAAAAAAABQAAAgAAAAB4AAAaCABAAAAAAADoAEAAAAAAAGiACAB4AAAcSABAAAgAAAAoAEAAAAAAA" +
            "AUAAAIAAAAAeAAAGEgAQAAIAAAAKABAAAgAAABogAgAlAAAHIgAQAAMAAAAqABAAAAAAADoAEAAAAAAA" +
            "NgAABdIAEAADAAAAVgoQAAIAAAAtAACJwgAAgENVFQDyABAAAwAAAEYOEAADAAAARn4QAAAAAACoAAAJ" +
            "8vARAAAAAAAKABAAAgAAAAFAAAAAAAAARg4QAAMAAAAVAAABvhgAASIAAAhCABAAAAAAADoAEAABAAAA" +
            "GoAgAAAAAAAAAAAAHwAEAyoAEAAAAAAApwAACfIAEAACAAAAGgAQAAAAAAABQAAAAAAAAEb+EQAAAAAA" +
            "HgAACsIAEAAAAAAAVgUQAAAAAAACQAAAAAAAAAAAAAD/////AQAAAKcAAAnyABAAAwAAACoAEAAAAAAA" +
            "AUAAAAAAAABG/hEAAAAAAKcAAAnyABAABAAAADoAEAAAAAAAAUAAAAAAAABG/hEAAAAAAAAAAAfyABAA" +
            "AwAAAEYOEAADAAAARg4QAAQAAAA4AAAI8gAQAAMAAABGDhAAAwAAAFaFIAAAAAAAAQAAADIAAAryABAA" +
            "AgAAAEYOEAACAAAABoAgAAAAAAABAAAARg4QAAMAAAAhAAAK8gAQAAMAAAAGABAAAAAAAAJAAAACAAAA" +
            "AwAAAAQAAAAFAAAAHwAEAwoAEAADAAAAHgAACsIAEAAAAAAAVgUQAAAAAAACQAAAAAAAAAAAAAD+////" +
            "AgAAAKcAAAnyABAABAAAACoAEAAAAAAAAUAAAAAAAABG/hEAAAAAAKcAAAnyABAABQAAADoAEAAAAAAA" +
            "AUAAAAAAAABG/hEAAAAAAAAAAAfyABAABAAAAEYOEAAEAAAARg4QAAUAAAAyAAAK8gAQAAIAAABGDhAA" +
            "BAAAAKaKIAAAAAAAAQAAAEYOEAACAAAAFQAAAR8ABAMaABAAAwAAAB4AAArCABAAAAAAAFYFEAAAAAAA" +
            "AkAAAAAAAAAAAAAA/f///wMAAACnAAAJ8gAQAAQAAAAqABAAAAAAAAFAAAAAAAAARv4RAAAAAACnAAAJ" +
            "8gAQAAUAAAA6ABAAAAAAAAFAAAAAAAAARv4RAAAAAAAAAAAH8gAQAAQAAABGDhAABAAAAEYOEAAFAAAA" +
            "MgAACvIAEAACAAAARg4QAAQAAAD2jyAAAAAAAAEAAABGDhAAAgAAABUAAAEfAAQDKgAQAAMAAAAeAAAK" +
            "wgAQAAAAAABWBRAAAAAAAAJAAAAAAAAAAAAAAPz///8EAAAApwAACfIAEAAEAAAAKgAQAAAAAAABQAAA" +
            "AAAAAEb+EQAAAAAApwAACfIAEAAFAAAAOgAQAAAAAAABQAAAAAAAAEb+EQAAAAAAAAAAB/IAEAAEAAAA" +
            "Rg4QAAQAAABGDhAABQAAADIAAAryABAAAgAAAEYOEAAEAAAABoAgAAAAAAACAAAARg4QAAIAAAAVAAAB" +
            "HwAEAzoAEAADAAAAHgAACsIAEAAAAAAAVgUQAAAAAAACQAAAAAAAAAAAAAD7////BQAAAKcAAAnyABAA" +
            "AwAAACoAEAAAAAAAAUAAAAAAAABG/hEAAAAAAKcAAAnyABAABAAAADoAEAAAAAAAAUAAAAAAAABG/hEA" +
            "AAAAAAAAAAfyABAAAwAAAEYOEAADAAAARg4QAAQAAAAyAAAK8gAQAAIAAABGDhAAAwAAAFaFIAAAAAAA" +
            "AgAAAEYOEAACAAAAFQAAASEAAApSABAAAAAAAAYAEAAAAAAAAkAAAAYAAAAAAAAABwAAAAAAAAAfAAQD" +
            "CgAQAAAAAAAeAAAKkgAQAAAAAABWBRAAAAAAAAJAAAD6////AAAAAAAAAAAGAAAApwAACfIAEAADAAAA" +
            "CgAQAAAAAAABQAAAAAAAAEb+EQAAAAAApwAACfIAEAAEAAAAOgAQAAAAAAABQAAAAAAAAEb+EQAAAAAA" +
            "AAAAB/IAEAADAAAARg4QAAMAAABGDhAABAAAADIAAAryABAAAgAAAEYOEAADAAAApoogAAAAAAACAAAA" +
            "Rg4QAAIAAAAVAAABHwAEAyoAEAAAAAAAHgAACjIAEAAAAAAAVgUQAAAAAAACQAAA+f///wcAAAAAAAAA" +
            "AAAAAKcAAAnyABAAAwAAAAoAEAAAAAAAAUAAAAAAAABG/hEAAAAAAKcAAAnyABAAAAAAABoAEAAAAAAA" +
            "AUAAAAAAAABG/hEAAAAAAAAAAAfyABAAAAAAAEYOEAAAAAAARg4QAAMAAAAyAAAK8gAQAAIAAABGDhAA" +
            "AAAAAPaPIAAAAAAAAgAAAEYOEAACAAAAFQAAATYAAAQSABAAAQAAAAoQAgCkAAAH8uARAAAAAABGDhAA" +
            "AQAAAEYOEAACAAAAFQAAAT4AAAFTVEFUlAAAAFoAAAAGAAAAAAAAAAIAAAAPAAAAHAAAAAAAAAACAAAA" +
            "CQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAEAAAA="
        );

        /// <summary>
        /// CS 5.0 3x3 Convolution (Sobel Edge & Laplacian Sharpening with 18x18 LDS Apron).
        /// </summary>
        public static byte[] CsConvolution3x3Bytecode { get; } = Convert.FromBase64String(
            "RFhCQ6+JAB2f02pnZ4zdmP3U8YABAAAAIBIAAAUAAAA0AAAAWAIAAGgCAAB4AgAAhBEAAFJERUYcAgAA" +
            "AQAAALwAAAADAAAAPAAAAAAFU0MAgQAA9AEAAFJEMTE8AAAAGAAAACAAAAAoAAAAJAAAAAwAAAAAAAAA" +
            "nAAAAAIAAAAFAAAABAAAAP////8AAAAAAQAAAA0AAACmAAAABAAAAAUAAAAEAAAA/////wAAAAABAAAA" +
            "DQAAALEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAABAAAAQ29udklucHV0AENvbnZPdXRwdXQAQ29u" +
            "dlBhcmFtcwCxAAAABAAAANQAAAAQAAAAAAAAAAAAAAB0AQAAAAAAAAQAAAACAAAAhAEAAAAAAAD/////" +
            "AAAAAP////8AAAAAqAEAAAQAAAAEAAAAAgAAAIQBAAAAAAAA/////wAAAAD/////AAAAALMBAAAIAAAA" +
            "BAAAAAIAAACEAQAAAAAAAP////8AAAAA/////wAAAAC8AQAADAAAAAQAAAACAAAA0AEAAAAAAAD/////" +
            "AAAAAP////8AAAAAQ29udldpZHRoAGR3b3JkAAAAEwABAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "fgEAAENvbnZIZWlnaHQAQ29udk1vZGUAQ29udlN0cmVuZ3RoAGZsb2F0AKsAAAMAAQABAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAMkBAABNaWNyb3NvZnQgKFIpIEhMU0wgU2hhZGVyIENvbXBpbGVyIDEwLjEA" +
            "SVNHTggAAAAAAAAACAAAAE9TR04IAAAAAAAAAAgAAABTSEVYBA8AAFAABQDBAwAAaggAAVkAAARGjiAA" +
            "AAAAAAEAAABYGAAEAHAQAAAAAABVVQAAnBgABADgEQAAAAAAVVUAAF8AAAIyEAIAXwAAAjIgAgBoAAAC" +
            "BgAAAKAAAAUA8BEAAAAAACABAAASAAAAmwAABBAAAAAQAAAAAQAAACMAAAryABAAAAAAAEYVAgACQAAA" +
            "EAAAABAAAAAQAAAAEAAAAEYlAgAeAAALMgAQAAEAAABGgCAAAAAAAAAAAAACQAAA//////////8AAAAA" +
            "AAAAAB4AAAZCABAAAQAAABogAgABQAAAAQAAACkAAAaCABAAAQAAAAogAgABQAAABAAAAB4AAAcSABAA" +
            "AgAAADoAEAABAAAAAUAAABAAAAAlAAAHYgAQAAMAAAAGAxAAAAAAAAYBEAABAAAANgAABYIAEAADAAAA" +
            "AUAAAAAAAAAtAACJwgAAgENVFQDyABAABAAAAJYPEAADAAAARn4QAAAAAACoAAAJ8vARAAAAAAAqABAA" +
            "AQAAAAoAEAACAAAARg4QAAQAAAAgAAAJ8gAQAAQAAAAGJQIAAkAAAAAAAAAPAAAAAAAAAA8AAAAfAAAC" +
            "CiACAB4AAAciABAAAgAAAAoAEAAAAAAAAUAAAP////8kAAAHIgAQAAIAAAAaABAAAgAAAAFAAAAAAAAA" +
            "JQAABxIAEAADAAAACgAQAAEAAAAaABAAAgAAAC0AAInCAACAQ1UVAPIAEAAFAAAAhg8QAAMAAABGfhAA" +
            "AAAAAKgAAAny8BEAAAAAACoAEAABAAAAAUAAAAAAAABGDhAABQAAABUAAAEfAAQDGgAQAAQAAAAeAAAH" +
            "IgAQAAIAAAAKABAAAAAAAAFAAAABAAAAJQAABxIAEAAFAAAACgAQAAEAAAAaABAAAgAAADYAAAXiABAA" +
            "BQAAAKYPEAADAAAALQAAicIAAIBDVRUA8gAQAAUAAABGDhAABQAAAEZ+EAAAAAAAqAAACfLwEQAAAAAA" +
            "KgAQAAEAAAABQAAAEAEAAEYOEAAFAAAAFQAAAR8AAAIaIAIAHgAAByIAEAACAAAAOgAQAAAAAAABQAAA" +
            "/////yQAAAciABAAAgAAABoAEAACAAAAAUAAAAAAAAAlAAAHIgAQAAUAAAAaABAAAQAAABoAEAACAAAA" +
            "NgAABdIAEAAFAAAAVg8QAAMAAAAtAACJwgAAgENVFQDyABAABQAAAEYOEAAFAAAARn4QAAAAAACoAAAJ" +
            "8vARAAAAAAABQAAAAAAAAAoAEAACAAAARg4QAAUAAAAVAAABHwAEAzoAEAAEAAAAHgAAByIAEAACAAAA" +
            "OgAQAAAAAAABQAAAAQAAACUAAAciABAABQAAABoAEAABAAAAGgAQAAIAAAA2AAAF0gAQAAUAAABWDxAA" +
            "AwAAAC0AAInCAACAQ1UVAPIAEAADAAAARg4QAAUAAABGfhAAAAAAAKgAAAny8BEAAAAAAAFAAAARAAAA" +
            "CgAQAAIAAABGDhAAAwAAABUAAAEBAAAH8gAQAAMAAACmDxAABAAAAEYEEAAEAAAAHwAEAwoAEAADAAAA" +
            "HgAACmIAEAACAAAABgMQAAAAAAACQAAAAAAAAP//////////AAAAACQAAApiABAAAgAAAFYGEAACAAAA" +
            "AkAAAAAAAAAAAAAAAAAAAAAAAAAlAAAHMgAQAAQAAABGABAAAQAAAJYFEAACAAAANgAACMIAEAAEAAAA" +
            "AkAAAAAAAAAAAAAAAAAAAAAAAAAtAACJwgAAgENVFQDiABAAAgAAAEYOEAAEAAAANnkQAAAAAACoAAAJ" +
            "cvARAAAAAAABQAAAAAAAAAFAAAAAAAAAlgcQAAIAAAAVAAABHwAEAxoAEAADAAAAHgAACmIAEAACAAAA" +
            "BgMQAAAAAAACQAAAAAAAAAEAAAD/////AAAAACUAAAcSABAABAAAAAoAEAABAAAAGgAQAAIAAAAkAAAH" +
            "IgAQAAIAAAAqABAAAgAAAAFAAAAAAAAAJQAAByIAEAAEAAAAGgAQAAEAAAAaABAAAgAAADYAAAjCABAA" +
            "BAAAAAJAAAAAAAAAAAAAAAAAAAAAAAAALQAAicIAAIBDVRUA4gAQAAIAAABGDhAABAAAADZ5EAAAAAAA" +
            "qAAACXLwEQAAAAAAAUAAAAAAAAABQAAAEAEAAJYHEAACAAAAFQAAAR8ABAMqABAAAwAAAB4AAApiABAA" +
            "AgAAAAYDEAAAAAAAAkAAAAAAAAD/////AQAAAAAAAAAkAAAHIgAQAAIAAAAaABAAAgAAAAFAAAAAAAAA" +
            "JQAABzIAEAAEAAAARgAQAAEAAACWBRAAAgAAADYAAAjCABAABAAAAAJAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "LQAAicIAAIBDVRUA4gAQAAIAAABGDhAABAAAADZ5EAAAAAAAqAAACXLwEQAAAAAAAUAAABEAAAABQAAA" +
            "AAAAAJYHEAACAAAAFQAAAR8ABAM6ABAAAwAAAB4AAApiABAAAgAAAAYDEAAAAAAAAkAAAAAAAAABAAAA" +
            "AQAAAAAAAAAlAAAHMgAQAAMAAABGABAAAQAAAJYFEAACAAAANgAACMIAEAADAAAAAkAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAtAACJwgAAgENVFQDiABAAAgAAAEYOEAADAAAANnkQAAAAAACoAAAJcvARAAAAAAABQAAA" +
            "EQAAAAFAAAAQAQAAlgcQAAIAAAAVAAABvhgAASIAAAgyABAAAQAAAMYAEAAAAAAARoAgAAAAAAAAAAAA" +
            "AQAABxIAEAABAAAAGgAQAAEAAAAKABAAAQAAAB8ABAMKABAAAQAAAB4AAAYSABAAAQAAAAogAgABQAAA" +
            "AQAAAKcAAAnyABAAAwAAACoAEAABAAAACgAQAAIAAABG/hEAAAAAAB8AAAQqgCAAAAAAAAAAAAApAAAH" +
            "IgAQAAEAAAAKABAAAQAAAAFAAAAEAAAAHgAAByIAEAABAAAAGgAQAAEAAAABQAAA8P///6cAAAjiABAA" +
            "AgAAABogAgAaABAAAQAAAAb5EQAAAAAAEAAACiIAEAACAAAAlgcQAAIAAAACQAAA0LNZPlkXNz+Y3ZM9" +
            "AAAAAKcAAAhyABAABAAAABogAgAKABAAAgAAAEbyEQAAAAAAEAAACkIAEAACAAAARgIQAAQAAAACQAAA" +
            "0LNZPlkXNz+Y3ZM9AAAAAB4AAAeCABAAAgAAADoAEAABAAAAAUAAACAAAACnAAAIcgAQAAQAAAAaIAIA" +
            "OgAQAAIAAABG8hEAAAAAABAAAAoSABAABAAAAEYCEAAEAAAAAkAAANCzWT5ZFzc/mN2TPQAAAACnAAAJ" +
            "4gAQAAQAAAAqABAAAQAAABoAEAABAAAABvkRAAAAAAAQAAAKIgAQAAQAAACWBxAABAAAAAJAAADQs1k+" +
            "WRc3P5jdkz0AAAAApwAACXIAEAAFAAAAKgAQAAEAAAA6ABAAAgAAAEbyEQAAAAAAEAAACkIAEAAEAAAA" +
            "RgIQAAUAAAACQAAA0LNZPlkXNz+Y3ZM9AAAAAB4AAAaCABAABAAAABogAgABQAAAAgAAAKcAAAlyABAA" +
            "BQAAADoAEAAEAAAAGgAQAAEAAABG8hEAAAAAABAAAAoiABAAAQAAAEYCEAAFAAAAAkAAANCzWT5ZFzc/" +
            "mN2TPQAAAACnAAAJcgAQAAUAAAA6ABAABAAAAAoAEAACAAAARvIRAAAAAAAQAAAKEgAQAAUAAABGAhAA" +
            "BQAAAAJAAADQs1k+WRc3P5jdkz0AAAAApwAACeIAEAAFAAAAOgAQAAQAAAA6ABAAAgAAAAb5EQAAAAAA" +
            "EAAACoIAEAACAAAAlgcQAAUAAAACQAAA0LNZPlkXNz+Y3ZM9AAAAAAAAAAiCABAABAAAABoAEIBBAAAA" +
            "AgAAAAoAEAAEAAAAAAAACCIAEAAEAAAAKgAQAAQAAAAaABCAQQAAAAQAAAAyAAAJIgAQAAQAAAAaABAA" +
            "BAAAAAFAAAAAAABAOgAQAAQAAAAAAAAIQgAQAAQAAAAaABCAQQAAAAEAAAA6ABAAAgAAAAAAAAciABAA" +
            "BAAAACoAEAAEAAAAGgAQAAQAAAAyAAALIgAQAAIAAAAqABCAQQAAAAIAAAABQAAAAAAAQBoAEIBBAAAA" +
            "AgAAAAAAAAgiABAAAgAAAAoAEIBBAAAABAAAABoAEAACAAAAMgAACSIAEAABAAAACgAQAAUAAAABQAAA" +
            "AAAAQBoAEAABAAAAAAAAByIAEAABAAAAOgAQAAIAAAAaABAAAQAAAAAAAAciABAAAQAAABoAEAABAAAA" +
            "GgAQAAIAAAA4AAAHIgAQAAEAAAAaABAAAQAAABoAEAABAAAAMgAACSIAEAABAAAAGgAQAAQAAAAaABAA" +
            "BAAAABoAEAABAAAASwAABSIAEAABAAAAGgAQAAEAAAA4AAAIIgAQAAEAAAAaABAAAQAAADqAIAAAAAAA" +
            "AAAAADYgAAVyABAAAwAAAFYFEAABAAAAEgAAAacAAAjyABAABAAAABogAgAKABAAAgAAAEb+EQAAAAAA" +
            "HgAABiIAEAABAAAAGiACAAFAAAACAAAApwAACfIAEAACAAAAGgAQAAEAAAAKABAAAgAAAEb+EQAAAAAA" +
            "KQAABxIAEAABAAAACgAQAAEAAAABQAAABAAAAB4AAAcSABAAAQAAAAoAEAABAAAAAUAAAPD///+nAAAJ" +
            "8gAQAAUAAAAqABAAAQAAAAoAEAABAAAARv4RAAAAAAAeAAAHEgAQAAEAAAA6ABAAAQAAAAFAAAAgAAAA" +
            "pwAACfIAEAABAAAAKgAQAAEAAAAKABAAAQAAAEb+EQAAAAAAAAAAB/IAEAACAAAARg4QAAIAAABGDhAA" +
            "BAAAAAAAAAfyABAAAgAAAEYOEAAFAAAARg4QAAIAAAAAAAAH8gAQAAEAAABGDhAAAQAAAEYOEAACAAAA" +
            "MgAADfIAEAABAAAARg4QAAMAAAACQAAAAACgQAAAoEAAAKBAAACgQEYOEIBBAAAAAQAAAAAAAAjyABAA" +
            "AQAAAEYOEIBBAAAAAwAAAEYOEAABAAAAMiAACvIAEAADAAAA9o8gAAAAAAAAAAAARg4QAAEAAABGDhAA" +
            "AwAAABUAAAGkAAAH8uARAAAAAABGDhAAAAAAAEYOEAADAAAAFQAAAT4AAAFTVEFUlAAAAIUAAAAGAAAA" +
            "AAAAAAIAAAAcAAAAJwAAAAIAAAADAAAACQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAkAAAAAAAAA" +
            "AAAAAAAAAAAJAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAABAAAAAAAAAAEAAAA="
        );

        /// <summary>
        /// CS 5.0 2x Image Pyramid Downscale using 5x5 Binomial Gaussian Filtering.
        /// </summary>
        public static byte[] CsPyramidDownBytecode { get; } = Convert.FromBase64String(
            "RFhCQ5FwaQ2djK3WxNfseulkLW4BAAAAiA8AAAUAAAA0AAAARAIAAFQCAABkAgAA7A4AAFJERUYIAgAA" +
            "AQAAANQAAAADAAAAPAAAAAAFU0MAgQAA3QEAAFJEMTE8AAAAGAAAACAAAAAoAAAAJAAAAAwAAAAAAAAA" +
            "nAAAAAIAAAAFAAAABAAAAP////8AAAAAAQAAAA0AAACtAAAABAAAAAUAAAAEAAAA/////wAAAAABAAAA" +
            "DQAAAL8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAABAAAAUHlyYW1pZERvd25JbnB1dABQeXJhbWlk" +
            "RG93bk91dHB1dABQeXJhbWlkRG93blBhcmFtcwCrq6u/AAAABAAAAOwAAAAQAAAAAAAAAAAAAACMAQAA" +
            "AAAAAAQAAAACAAAAnAEAAAAAAAD/////AAAAAP////8AAAAAwAEAAAQAAAAEAAAAAgAAAJwBAAAAAAAA" +
            "/////wAAAAD/////AAAAAMoBAAAIAAAABAAAAAIAAACcAQAAAAAAAP////8AAAAA/////wAAAADTAQAA" +
            "DAAAAAQAAAACAAAAnAEAAAAAAAD/////AAAAAP////8AAAAARHN0V2lkdGgAZHdvcmQAqwAAEwABAAEA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAlQEAAERzdEhlaWdodABTcmNXaWR0aABTcmNIZWlnaHQATWlj" +
            "cm9zb2Z0IChSKSBITFNMIFNoYWRlciBDb21waWxlciAxMC4xAKurq0lTR04IAAAAAAAAAAgAAABPU0dO" +
            "CAAAAAAAAAAIAAAAU0hFWIAMAABQAAUAIAMAAGoIAAFZAAAERo4gAAAAAAABAAAAWBgABABwEAAAAAAA" +
            "VVUAAJwYAAQA4BEAAAAAAFVVAABfAAACMgACAGgAAAIKAAAAmwAABBAAAAAQAAAAAQAAAFAAAAcyABAA" +
            "AAAAAEYAAgBGgCAAAAAAAAAAAAA8AAAHEgAQAAAAAAAaABAAAAAAAAoAEAAAAAAAHwAEAwoAEAAAAAAA" +
            "PgAAARUAAAEpAAAJMgAQAAAAAABGAAIAAkAAAAEAAAABAAAAAAAAAAAAAAAeAAALwgAQAAAAAACmjiAA" +
            "AAAAAAAAAAACQAAAAAAAAAAAAAD//////////x4AAAryABAAAQAAABYAEAAAAAAAAkAAAP7////+////" +
            "/////wIAAAAkAAAKcgAQAAEAAABGAhAAAQAAAAJAAAAAAAAAAAAAAAAAAAAAAAAAJQAAB3IAEAACAAAA" +
            "pgsQAAAAAABmCBAAAQAAADYAAAWCABAAAgAAAAFAAAAAAAAALQAAicIAAIBDVRUA8gAQAAMAAACWDxAA" +
            "AgAAAEZ+EAAAAAAALQAAicIAAIBDVRUA8gAQAAQAAACGDxAAAgAAAEZ+EAAAAAAAOAAACvIAEAAEAAAA" +
            "Rg4QAAQAAAACQAAAAACAPAAAgDwAAIA8AACAPDIAAAzyABAAAwAAAEYOEAADAAAAAkAAAAAAgDsAAIA7" +
            "AACAOwAAgDtGDhAABAAAACUAAAcyABAABAAAAOYKEAAAAAAARgAQAAAAAAA2AAAFwgAQAAQAAACmDhAA" +
            "AgAAAC0AAInCAACAQ1UVAPIAEAAFAAAAhg8QAAQAAABGfhAAAAAAADIAAAzyABAAAwAAAEYOEAAFAAAA" +
            "AkAAAAAAwDwAAMA8AADAPAAAwDxGDhAAAwAAACMAAA4yABAAAQAAAEYAAgACQAAAAgAAAAIAAAAAAAAA" +
            "AAAAAAJAAAABAAAAAQAAAAAAAAAAAAAAJQAABzIAEAAFAAAA5goQAAAAAABGABAAAQAAADYAAAXCABAA" +
            "BQAAAKYOEAAEAAAALQAAicIAAIBDVRUA8gAQAAYAAACGDxAABQAAAEZ+EAAAAAAAMgAADPIAEAADAAAA" +
            "Rg4QAAYAAAACQAAAAACAPAAAgDwAAIA8AACAPEYOEAADAAAAJQAABxIAEAABAAAAKgAQAAAAAAA6ABAA" +
            "AQAAADYAAAViABAAAQAAAKYLEAAFAAAALQAAicIAAIBDVRUA8gAQAAYAAABGChAAAQAAAEZ+EAAAAAAA" +
            "MgAADPIAEAADAAAARg4QAAYAAAACQAAAAACAOwAAgDsAAIA7AACAO0YOEAADAAAAHgAACjIAEAAAAAAA" +
            "VgUQAAAAAAACQAAA/////wIAAAAAAAAAAAAAACQAAAcSABAAAAAAAAoAEAAAAAAAAUAAAAAAAAAlAAAH" +
            "IgAQAAYAAAA6ABAAAAAAAAoAEAAAAAAANgAABVIAEAAGAAAAVgcQAAIAAAAtAACJwgAAgENVFQDyABAA" +
            "BwAAAEYKEAAGAAAARn4QAAAAAAAyAAAM8gAQAAMAAABGDhAABwAAAAJAAAAAAIA8AACAPAAAgDwAAIA8" +
            "Rg4QAAMAAAA2AAAFQgAQAAIAAAAaABAABgAAAC0AAInCAACAQ1UVAPIAEAAHAAAAhg8QAAIAAABGfhAA" +
            "AAAAADIAAAzyABAAAwAAAEYOEAAHAAAAAkAAAAAAgD0AAIA9AACAPQAAgD1GDhAAAwAAADYAAAVSABAA" +
            "BwAAAAYDEAAEAAAANgAABSIAEAAHAAAAKgAQAAIAAAAtAACJwgAAgENVFQDyABAACAAAAEYKEAAHAAAA" +
            "Rn4QAAAAAAAyAAAM8gAQAAMAAABGDhAACAAAAAJAAAAAAMA9AADAPQAAwD0AAMA9Rg4QAAMAAAA2AAAF" +
            "UgAQAAgAAAAGAxAABQAAADYAAAUiABAACAAAABoAEAAHAAAALQAAicIAAIBDVRUA8gAQAAkAAABGChAA" +
            "CAAAAEZ+EAAAAAAAMgAADPIAEAADAAAARg4QAAkAAAACQAAAAACAPQAAgD0AAIA9AACAPUYOEAADAAAA" +
            "NgAABYIAEAABAAAAGgAQAAgAAAAtAACJwgAAgENVFQDyABAACQAAAMYKEAABAAAARn4QAAAAAAAyAAAM" +
            "8gAQAAMAAABGDhAACQAAAAJAAAAAAIA8AACAPAAAgDwAAIA8Rg4QAAMAAAA2AAAFggAQAAYAAAAaABAA" +
            "BAAAAC0AAInCAACAQ1UVAPIAEAAJAAAAxgoQAAYAAABGfhAAAAAAADIAAAzyABAAAwAAAEYOEAAJAAAA" +
            "AkAAAAAAwDwAAMA8AADAPAAAwDxGDhAAAwAAADYAAAUiABAAAgAAADoAEAAGAAAALQAAicIAAIBDVRUA" +
            "8gAQAAkAAABGDxAAAgAAAEZ+EAAAAAAAMgAADPIAEAADAAAARg4QAAkAAAACQAAAAADAPQAAwD0AAMA9" +
            "AADAPUYOEAADAAAALQAAicIAAIBDVRUA8gAQAAQAAABGDxAABAAAAEZ+EAAAAAAAMgAADPIAEAADAAAA" +
            "Rg4QAAQAAAACQAAAAAAQPgAAED4AABA+AAAQPkYOEAADAAAANgAABYIAEAAIAAAAGgAQAAIAAAAtAACJ" +
            "wgAAgENVFQDyABAABAAAAMYKEAAIAAAARn4QAAAAAAAyAAAM8gAQAAMAAABGDhAABAAAAAJAAAAAAMA9" +
            "AADAPQAAwD0AAMA9Rg4QAAMAAAA2AAAFIgAQAAEAAAA6ABAACAAAAC0AAInCAACAQ1UVAPIAEAAEAAAA" +
            "RgoQAAEAAABGfhAAAAAAADIAAAzyABAAAwAAAEYOEAAEAAAAAkAAAAAAwDwAAMA8AADAPAAAwDxGDhAA" +
            "AwAAADYAAAUiABAABgAAABoAEAAFAAAALQAAicIAAIBDVRUA8gAQAAQAAABGChAABgAAAEZ+EAAAAAAA" +
            "MgAADPIAEAADAAAARg4QAAQAAAACQAAAAACAPAAAgDwAAIA8AACAPEYOEAADAAAANgAABUIAEAACAAAA" +
            "GgAQAAYAAAAtAACJwgAAgENVFQDyABAABAAAAIYPEAACAAAARn4QAAAAAAAyAAAM8gAQAAMAAABGDhAA" +
            "BAAAAAJAAAAAAIA9AACAPQAAgD0AAIA9Rg4QAAMAAAA2AAAFggAQAAcAAAAqABAAAgAAAC0AAInCAACA" +
            "Q1UVAPIAEAAEAAAAxgoQAAcAAABGfhAAAAAAADIAAAzyABAAAwAAAEYOEAAEAAAAAkAAAAAAwD0AAMA9" +
            "AADAPQAAwD1GDhAAAwAAAC0AAInCAACAQ1UVAPIAEAAEAAAARg8QAAUAAABGfhAAAAAAADIAAAzyABAA" +
            "AwAAAEYOEAAEAAAAAkAAAAAAgD0AAIA9AACAPQAAgD1GDhAAAwAAADYAAAWCABAAAQAAADoAEAAHAAAA" +
            "LQAAicIAAIBDVRUA8gAQAAQAAADGChAAAQAAAEZ+EAAAAAAAMgAADPIAEAADAAAARg4QAAQAAAACQAAA" +
            "AACAPAAAgDwAAIA8AACAPEYOEAADAAAAJQAAB4IAEAAGAAAAOgAQAAAAAAAaABAAAAAAAC0AAInCAACA" +
            "Q1UVAPIAEAAAAAAAxgoQAAYAAABGfhAAAAAAADIAAAzyABAAAAAAAEYOEAAAAAAAAkAAAAAAgDsAAIA7" +
            "AACAOwAAgDtGDhAAAwAAADYAAAUiABAAAgAAADoAEAAGAAAALQAAicIAAIBDVRUA8gAQAAMAAABGDxAA" +
            "AgAAAEZ+EAAAAAAAMgAADPIAEAAAAAAARg4QAAMAAAACQAAAAACAPAAAgDwAAIA8AACAPEYOEAAAAAAA" +
            "NgAABdIAEAACAAAABgoQAAcAAAAtAACJwgAAgENVFQDyABAAAwAAAEYOEAACAAAARn4QAAAAAAAyAAAM" +
            "8gAQAAAAAABGDhAAAwAAAAJAAAAAAMA8AADAPAAAwDwAAMA8Rg4QAAAAAAA2AAAF0gAQAAIAAAAGChAA" +
            "CAAAAC0AAInCAACAQ1UVAPIAEAADAAAARg4QAAIAAABGfhAAAAAAADIAAAzyABAAAAAAAEYOEAADAAAA" +
            "AkAAAAAAgDwAAIA8AACAPAAAgDxGDhAAAAAAADYAAAXSABAAAgAAAAYKEAABAAAALQAAicIAAIBDVRUA" +
            "8gAQAAEAAABGDhAAAgAAAEZ+EAAAAAAAMgAADPIAEAAAAAAARg4QAAEAAAACQAAAAACAOwAAgDsAAIA7" +
            "AACAO0YOEAAAAAAApAAABvLgEQAAAAAARgUCAEYOEAAAAAAAPgAAAVNUQVSUAAAAXQAAAAoAAAAAAAAA" +
            "AQAAABkAAAANAAAAAgAAAAIAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGQAAAAAAAAAAAAAA" +
            "AAAAABcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAQAAAA=="
        );

        /// <summary>
        /// CS 5.0 2x Image Pyramid Upscale with Bilinear Interpolation.
        /// </summary>
        public static byte[] CsPyramidUpBytecode { get; } = Convert.FromBase64String(
            "RFhCQyVfv0jEz7oeXNUr098PYYgBAAAAJAcAAAUAAAA0AAAARAIAAFQCAABkAgAAiAYAAFJERUYIAgAA" +
            "AQAAAMwAAAADAAAAPAAAAAAFU0MAgQAA3wEAAFJEMTE8AAAAGAAAACAAAAAoAAAAJAAAAAwAAAAAAAAA" +
            "nAAAAAIAAAAFAAAABAAAAP////8AAAAAAQAAAA0AAACrAAAABAAAAAUAAAAEAAAA/////wAAAAABAAAA" +
            "DQAAALsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAABAAAAUHlyYW1pZFVwSW5wdXQAUHlyYW1pZFVw" +
            "T3V0cHV0AFB5cmFtaWRVcFBhcmFtcwCruwAAAAQAAADkAAAAEAAAAAAAAAAAAAAAhAEAAAAAAAAEAAAA" +
            "AgAAAJgBAAAAAAAA/////wAAAAD/////AAAAALwBAAAEAAAABAAAAAIAAACYAQAAAAAAAP////8AAAAA" +
            "/////wAAAADIAQAACAAAAAQAAAACAAAAmAEAAAAAAAD/////AAAAAP////8AAAAA0wEAAAwAAAAEAAAA" +
            "AgAAAJgBAAAAAAAA/////wAAAAD/////AAAAAFVwRHN0V2lkdGgAZHdvcmQAq6urAAATAAEAAQAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAACPAQAAVXBEc3RIZWlnaHQAVXBTcmNXaWR0aABVcFNyY0hlaWdodABN" +
            "aWNyb3NvZnQgKFIpIEhMU0wgU2hhZGVyIENvbXBpbGVyIDEwLjEAq0lTR04IAAAAAAAAAAgAAABPU0dO" +
            "CAAAAAAAAAAIAAAAU0hFWBwEAABQAAUABwEAAGoIAAFZAAAERo4gAAAAAAABAAAAWBgABABwEAAAAAAA" +
            "VVUAAJwYAAQA4BEAAAAAAFVVAABfAAACMgACAGgAAAIFAAAAmwAABBAAAAAQAAAAAQAAAFAAAAcyABAA" +
            "AAAAAEYAAgBGgCAAAAAAAAAAAAA8AAAHEgAQAAAAAAAaABAAAAAAAAoAEAAAAAAAHwAEAwoAEAAAAAAA" +
            "PgAAARUAAAFWAAAEMgAQAAAAAABGAAIAAAAACjIAEAAAAAAARgAQAAAAAAACQAAAAAAAPwAAAD8AAAAA" +
            "AAAAAFYAAAbyABAAAQAAAEaOIAAAAAAAAAAAAA4AAAcyABAAAAAAAEYAEAAAAAAARgAQAAEAAAAyAAAM" +
            "MgAQAAAAAABGABAAAAAAAOYKEAABAAAAAkAAAAAAAL8AAAC/AAAAAAAAAABBAAAFwgAQAAAAAAAGBBAA" +
            "AAAAABsAAAUyABAAAQAAAOYKEAAAAAAAHgAACsIAEAABAAAABgQQAAEAAAACQAAAAAAAAAAAAAABAAAA" +
            "AQAAAAAAAAgyABAAAAAAAOYKEIBBAAAAAAAAAEYAEAAAAAAAHgAAC8IAEAAAAAAApo4gAAAAAAAAAAAA" +
            "AkAAAAAAAAAAAAAA//////////8kAAAKMgAQAAEAAABGABAAAQAAAAJAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "JQAABzIAEAACAAAA5goQAAAAAABGABAAAQAAADYAAAVCABAAAgAAAAFAAAAAAAAALQAAicIAAIBDVRUA" +
            "8gAQAAMAAABGChAAAgAAAEZ+EAAAAAAAJAAACjIAEAABAAAA5goQAAEAAAACQAAAAAAAAAAAAAAAAAAA" +
            "AAAAACUAAAcyABAAAQAAAOYKEAAAAAAARgAQAAEAAAA2AAAFwgAQAAEAAABWCRAAAgAAAC0AAInCAACA" +
            "Q1UVAPIAEAAEAAAAhg8QAAEAAABGfhAAAAAAADYAAAWCABAAAgAAABoAEAABAAAALQAAicIAAIBDVRUA" +
            "8gAQAAIAAADGChAAAgAAAEZ+EAAAAAAALQAAicIAAIBDVRUA8gAQAAEAAABGDxAAAQAAAEZ+EAAAAAAA" +
            "AAAACPIAEAAEAAAARg4QgEEAAAADAAAARg4QAAQAAAAyAAAJ8gAQAAMAAAAGABAAAAAAAEYOEAAEAAAA" +
            "Rg4QAAMAAAAAAAAI8gAQAAEAAABGDhCAQQAAAAIAAABGDhAAAQAAADIAAAnyABAAAQAAAAYAEAAAAAAA" +
            "Rg4QAAEAAABGDhAAAgAAAAAAAAjyABAAAQAAAEYOEIBBAAAAAwAAAEYOEAABAAAAMgAACfIAEAAAAAAA" +
            "VgUQAAAAAABGDhAAAQAAAEYOEAADAAAApAAABvLgEQAAAAAARgUCAEYOEAAAAAAAPgAAAVNUQVSUAAAA" +
            "IgAAAAUAAAAAAAAAAQAAAAsAAAAGAAAAAgAAAAIAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "BAAAAAAAAAAAAAAAAAAAAAMAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAA=="
        );

        /// <summary>
        /// CS 5.0 Focus Stacking Sharpness Measure (Modified Laplacian Energy).
        /// </summary>
        public static byte[] CsFocusMeasureBytecode { get; } = Convert.FromBase64String(
            "RFhCQ3+9nzFIGi0LqDBVVRZTzLQBAAAARAcAAAUAAAA0AAAAaAIAAHgCAACIAgAAqAYAAFJERUYsAgAA" +
            "AQAAAMgAAAADAAAAPAAAAAAFU0MAgQAABAIAAFJEMTE8AAAAGAAAACAAAAAoAAAAJAAAAAwAAAAAAAAA" +
            "nAAAAAIAAAAFAAAABAAAAP////8AAAAAAQAAAA0AAACnAAAABAAAAAUAAAAEAAAA/////wAAAAABAAAA" +
            "AQAAALkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAABAAAARm9jdXNJbnB1dABGb2N1c0VuZXJneU91" +
            "dHB1dABGb2N1c1BhcmFtcwCrq6u5AAAABAAAAOAAAAAQAAAAAAAAAAAAAACAAQAAAAAAAAQAAAACAAAA" +
            "lAEAAAAAAAD/////AAAAAP////8AAAAAuAEAAAQAAAAEAAAAAgAAAJQBAAAAAAAA/////wAAAAD/////" +
            "AAAAAMQBAAAIAAAABAAAAAAAAACUAQAAAAAAAP////8AAAAA/////wAAAADQAQAADAAAAAQAAAAAAAAA" +
            "4AEAAAAAAAD/////AAAAAP////8AAAAARm9jdXNXaWR0aABkd29yZACrq6sAABMAAQABAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAIsBAABGb2N1c0hlaWdodABGb2N1c1JhZGl1cwBGb2N1c1BhZABmbG9hdACr" +
            "AAADAAEAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADZAQAATWljcm9zb2Z0IChSKSBITFNMIFNoYWRl" +
            "ciBDb21waWxlciAxMC4xAElTR04IAAAAAAAAAAgAAABPU0dOCAAAAAAAAAAIAAAAU0hFWBgEAABQAAUA" +
            "BgEAAGoIAAFZAAAERo4gAAAAAAABAAAAWBgABABwEAAAAAAAVVUAAJwYAAQA4BEAAAAAAFVVAABfAAAC" +
            "MgACAGgAAAIFAAAAmwAABBAAAAAQAAAAAQAAAFAAAAcyABAAAAAAAEYAAgBGgCAAAAAAAAAAAAA8AAAH" +
            "EgAQAAAAAAAaABAAAAAAAAoAEAAAAAAAHwAEAwoAEAAAAAAAPgAAARUAAAEeAAALMgAQAAAAAABGgCAA" +
            "AAAAAAAAAAACQAAA//////////8AAAAAAAAAADYAAAQyABAAAQAAAEYAAgA2AAAFQgAQAAEAAAABQAAA" +
            "AAAAAC0AAInCAACAQ1UVAHIAEAACAAAARgoQAAEAAABGfhAAAAAAABAAAApCABAAAAAAAEYCEAACAAAA" +
            "AkAAANCzWT5ZFzc/mN2TPQAAAAAeAAAJ8gAQAAIAAAAGBQIAAkAAAP////8BAAAA/////wEAAAAkAAAK" +
            "UgAQAAIAAAAGAhAAAgAAAAJAAAAAAAAAAAAAAAAAAAAAAAAAJQAABzIAEAADAAAARgAQAAAAAACGABAA" +
            "AgAAADYAAAXCABAAAwAAAFYJEAABAAAALQAAicIAAIBDVRUAcgAQAAQAAACGDxAAAwAAAEZ+EAAAAAAA" +
            "EAAACoIAEAAAAAAARgIQAAQAAAACQAAA0LNZPlkXNz+Y3ZM9AAAAACUAAAcyABAAAgAAAEYAEAAAAAAA" +
            "1gUQAAIAAAA2AAAFwgAQAAIAAACmDhAAAwAAAC0AAInCAACAQ1UVANIAEAADAAAAhg8QAAIAAADGeRAA" +
            "AAAAABAAAAoSABAAAAAAAIYDEAADAAAAAkAAANCzWT5ZFzc/mN2TPQAAAAA2AAAFggAQAAEAAAAaABAA" +
            "AwAAAC0AAInCAACAQ1UVAHIAEAADAAAAxgoQAAEAAABGfhAAAAAAABAAAAoiABAAAAAAAEYCEAADAAAA" +
            "AkAAANCzWT5ZFzc/mN2TPQAAAAA2AAAF0gAQAAIAAAAGChAAAQAAAC0AAInCAACAQ1UVAHIAEAABAAAA" +
            "Rg4QAAIAAABGfhAAAAAAABAAAAoSABAAAQAAAEYCEAABAAAAAkAAANCzWT5ZFzc/mN2TPQAAAAAyAAAK" +
            "ggAQAAAAAAAqABAAAAAAAAFAAAAAAABAOgAQgEEAAAAAAAAAAAAACBIAEAAAAAAACgAQgEEAAAAAAAAA" +
            "OgAQAAAAAAAyAAAKIgAQAAAAAAAqABAAAAAAAAFAAAAAAABAGgAQgEEAAAAAAAAAAAAACCIAEAAAAAAA" +
            "CgAQgEEAAAABAAAAGgAQAAAAAAAAAAAJEgAQAAAAAAAaABCAgQAAAAAAAAAKABCAgQAAAAAAAACkAAAG" +
            "8uARAAAAAABGBQIABgAQAAAAAAA+AAABU1RBVJQAAAAhAAAABQAAAAAAAAABAAAACgAAAAUAAAACAAAA" +
            "AgAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFAAAAAAAAAAAAAAAAAAAABgAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAA"
        );

        /// <summary>
        /// CS 5.0 Focus Stacking Blend (Maximum Energy Pixel-wise Selection).
        /// </summary>
        public static byte[] CsFocusBlendBytecode { get; } = Convert.FromBase64String(
            "RFhCQ4JnX/8t73HNle+lYI8ZiHEBAAAAiAUAAAUAAAA0AAAAvAIAAMwCAADcAgAA7AQAAFJERUaAAgAA" +
            "AQAAABwBAAAFAAAAPAAAAAAFU0MAgQAAWAIAAFJEMTE8AAAAGAAAACAAAAAoAAAAJAAAAAwAAAAAAAAA" +
            "3AAAAAIAAAAFAAAABAAAAP////8AAAAAAQAAAA0AAADnAAAAAgAAAAUAAAAEAAAA/////wEAAAABAAAA" +
            "AQAAAPMAAAAEAAAABQAAAAQAAAD/////AAAAAAEAAAANAAAA/QAAAAQAAAAFAAAABAAAAP////8BAAAA" +
            "AQAAAAEAAAAIAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAQAAAFNsaWNlQ29sb3IAU2xpY2VFbmVy" +
            "Z3kAQmVzdENvbG9yAEJlc3RFbmVyZ3kARm9jdXNCbGVuZFBhcmFtcwCrq6sIAQAABAAAADQBAAAQAAAA" +
            "AAAAAAAAAADUAQAAAAAAAAQAAAACAAAA6AEAAAAAAAD/////AAAAAP////8AAAAADAIAAAQAAAAEAAAA" +
            "AgAAAOgBAAAAAAAA/////wAAAAD/////AAAAABgCAAAIAAAABAAAAAIAAADoAQAAAAAAAP////8AAAAA" +
            "/////wAAAAAlAgAADAAAAAQAAAAAAAAANAIAAAAAAAD/////AAAAAP////8AAAAAQmxlbmRXaWR0aABk" +
            "d29yZACrq6sAABMAAQABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAN8BAABCbGVuZEhlaWdodABJc0Zp" +
            "cnN0U2xpY2UAQmxlbmRQYWQAZmxvYXQAAAADAAEAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAuAgAA" +
            "TWljcm9zb2Z0IChSKSBITFNMIFNoYWRlciBDb21waWxlciAxMC4xAElTR04IAAAAAAAAAAgAAABPU0dO" +
            "CAAAAAAAAAAIAAAAU0hFWAgCAABQAAUAggAAAGoIAAFZAAAERo4gAAAAAAABAAAAWBgABABwEAAAAAAA" +
            "VVUAAFgYAAQAcBAAAQAAAFVVAACcGAAEAOARAAAAAABVVQAAnBgABADgEQABAAAAVVUAAF8AAAIyAAIA" +
            "aAAAAgIAAACbAAAEEAAAABAAAAABAAAAUAAABzIAEAAAAAAARgACAEaAIAAAAAAAAAAAADwAAAcSABAA" +
            "AAAAABoAEAAAAAAACgAQAAAAAAAfAAQDCgAQAAAAAAA+AAABFQAAATYAAAQyABAAAAAAAEYAAgA2AAAI" +
            "wgAQAAAAAAACQAAAAAAAAAAAAAAAAAAAAAAAAC0AAInCAACAQ1UVAPIAEAABAAAARg8QAAAAAABGfhAA" +
            "AAAAAC0AAInCAACAQ1UVABIAEAAAAAAARg4QAAAAAABGfhAAAQAAAB8ABAQqgCAAAAAAAAAAAACkAAAG" +
            "8uARAAAAAABGBQIARg4QAAEAAACkAAAG8uARAAEAAABGBQIABgAQAAAAAAASAAABowAAiMIAAIBDVRUA" +
            "IgAQAAAAAABGBQIAFu4RAAEAAAAxAAAHIgAQAAAAAAAaABAAAAAAAAoAEAAAAAAAHwAEAxoAEAAAAAAA" +
            "pAAABvLgEQAAAAAARgUCAEYOEAABAAAApAAABvLgEQABAAAARgUCAAYAEAAAAAAAFQAAARUAAAE+AAAB" +
            "U1RBVJQAAAAVAAAAAgAAAAAAAAABAAAAAQAAAAAAAAACAAAABAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAADAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAA"
        );

        /// <summary>
        /// CS 5.0 HDR Tone Mapping (Exposure, Reinhard, ACES Filmic, Gamma).
        /// </summary>
        public static byte[] CsHdrToneMappingBytecode { get; } = Convert.FromBase64String(
            "RFhCQz97d/FEdBgR5EYqsEVKMH0BAAAAgAcAAAUAAAA0AAAA6AIAAPgCAAAIAwAA5AYAAFJERUasAgAA" +
            "AQAAALwAAAADAAAAPAAAAAAFU0MAgQAAhAIAAFJEMTE8AAAAGAAAACAAAAAoAAAAJAAAAAwAAAAAAAAA" +
            "nAAAAAIAAAAFAAAABAAAAP////8AAAAAAQAAAA0AAAClAAAABAAAAAUAAAAEAAAA/////wAAAAABAAAA" +
            "DQAAAK8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAABAAAASGRySW5wdXQAU2RyT3V0cHV0AEhkclBh" +
            "cmFtcwCrq6uvAAAABgAAANQAAAAgAAAAAAAAAAAAAADEAQAAAAAAAAQAAAACAAAA1AEAAAAAAAD/////" +
            "AAAAAP////8AAAAA+AEAAAQAAAAEAAAAAgAAANQBAAAAAAAA/////wAAAAD/////AAAAAAICAAAIAAAA" +
            "BAAAAAIAAADUAQAAAAAAAP////8AAAAA/////wAAAAASAgAADAAAAAQAAAACAAAAJAIAAAAAAAD/////" +
            "AAAAAP////8AAAAASAIAABAAAAAEAAAAAgAAACQCAAAAAAAA/////wAAAAD/////AAAAAFECAAAUAAAA" +
            "DAAAAAAAAABgAgAAAAAAAP////8AAAAA/////wAAAABIZHJXaWR0aABkd29yZACrAAATAAEAAQAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAADNAQAASGRySGVpZ2h0AFRvbmVNYXBwaW5nTW9kZQBFeHBvc3VyZQBm" +
            "bG9hdACrq6sAAAMAAQABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABsCAABIZHJHYW1tYQBIZHJQYWQA" +
            "ZmxvYXQzAKsBAAMAAQADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFgCAABNaWNyb3NvZnQgKFIpIEhM" +
            "U0wgU2hhZGVyIENvbXBpbGVyIDEwLjEASVNHTggAAAAAAAAACAAAAE9TR04IAAAAAAAAAAgAAABTSEVY" +
            "1AMAAFAABQD1AAAAaggAAVkAAARGjiAAAAAAAAIAAABYGAAEAHAQAAAAAABVVQAAnBgABADgEQAAAAAA" +
            "VVUAAF8AAAIyAAIAaAAAAgUAAACbAAAEEAAAABAAAAABAAAAUAAABzIAEAAAAAAARgACAEaAIAAAAAAA" +
            "AAAAADwAAAcSABAAAAAAABoAEAAAAAAACgAQAAAAAAAfAAQDCgAQAAAAAAA+AAABFQAAATYAAAQyABAA" +
            "AAAAAEYAAgA2AAAIwgAQAAAAAAACQAAAAAAAAAAAAAAAAAAAAAAAAC0AAInCAACAQ1UVAPIAEAAAAAAA" +
            "Rg4QAAAAAABGfhAAAAAAABkAAAYSABAAAQAAADqAIAAAAAAAAAAAADgAAAfiABAAAQAAAAYJEAAAAAAA" +
            "BgAQAAEAAAAyAAAMcgAQAAIAAABGAhAAAAAAAAYAEAABAAAAAkAAAAAAgD8AAIA/AACAPwAAAAAOAAAH" +
            "cgAQAAIAAACWBxAAAQAAAEYCEAACAAAAIAAACBIAEAABAAAAKoAgAAAAAAAAAAAAAUAAAAEAAAAyAAAP" +
            "cgAQAAMAAACWBxAAAQAAAAJAAADXoyBA16MgQNejIEAAAAAAAkAAAI/C9TyPwvU8j8L1PAAAAAA4AAAH" +
            "cgAQAAMAAACWBxAAAQAAAEYCEAADAAAAMgAAD3IAEAAEAAAAlgcQAAEAAAACQAAAH4UbQB+FG0AfhRtA" +
            "AAAAAAJAAAA9Chc/PQoXPz0KFz8AAAAAMgAADHIAEAAEAAAAlgcQAAEAAABGAhAABAAAAAJAAAApXA8+" +
            "KVwPPilcDz4AAAAADiAAB3IAEAADAAAARgIQAAMAAABGAhAABAAAADYgAAXiABAAAQAAAFYOEAABAAAA" +
            "NwAACXIAEAABAAAABgAQAAEAAABGAhAAAwAAAJYHEAABAAAANwAACnIAEAABAAAApoogAAAAAAAAAAAA" +
            "RgIQAAEAAABGAhAAAgAAADQAAAiCABAAAQAAAAqAIAAAAAAAAQAAAAFAAABvEoM6DgAACoIAEAABAAAA" +
            "AkAAAAAAgD8AAIA/AACAPwAAgD86ABAAAQAAADQAAApyABAAAQAAAEYCEAABAAAAAkAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAvAAAFcgAQAAEAAABGAhAAAQAAADgAAAdyABAAAQAAAEYCEAABAAAA9g8QAAEAAAAZAAAF" +
            "cgAQAAEAAABGAhAAAQAAADMAAApyABAAAAAAAEYCEAABAAAAAkAAAAAAgD8AAIA/AACAPwAAAACkAAAG" +
            "8uARAAAAAABGBQIARg4QAAAAAAA+AAABU1RBVJQAAAAeAAAABQAAAAAAAAABAAAAEAAAAAEAAAACAAAA" +
            "AgAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAwAAAAIAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAA"
        );
    }
}