using System;

namespace ZeroGraphics.Imaging.Gpu.Shaders
{
    /// <summary>
    /// Precompiled Direct3D 11 DirectCompute HLSL Shader Bytecodes (Shader Model 5.0).
    /// Embedded as Base64 strings to eliminate runtime shader compiler dependencies.
    /// Features Local Data Share (groupshared LDS) caching for ultra-high memory bandwidth efficiency.
    /// </summary>
    public static class ComputeShaderBytecodes
    {
        /// <summary>
        /// CS 5.0 Color Transformation, Brightness, Contrast, Gamma and Threshold.
        /// </summary>
        public static byte[] CsColorAdjustBytecode { get; } = Convert.FromBase64String(
            "RFhCQ1GGvhsAYN78nxKE0h+BTo0BAAAAKAgAAAUAAAA0AAAA9AIAAAQDAAAUAwAAjAcAAFJERUa4AgAA" +
            "AQAAAMgAAAADAAAAPAAAAAAFU0MAgQAAkAIAAFJEMTE8AAAAGAAAACAAAAAoAAAAJAAAAAwAAAAAAAAA" +
            "nAAAAAIAAAAFAAAABAAAAP////8AAAAAAQAAAA0AAACnAAAABAAAAAUAAAAEAAAA/////wAAAAABAAAA" +
            "DQAAALMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAABAAAAQ29sb3JJbnB1dABDb2xvck91dHB1dABD" +
            "b2xvckNvbXB1dGVCdWZmZXIAq6uzAAAABwAAAOAAAAAgAAAAAAAAAAAAAAD4AQAAAAAAAAQAAAACAAAA" +
            "DAIAAAAAAAD/////AAAAAP////8AAAAAMAIAAAQAAAAEAAAAAgAAAAwCAAAAAAAA/////wAAAAD/////" +
            "AAAAADkCAAAIAAAABAAAAAIAAAAMAgAAAAAAAP////8AAAAA/////wAAAABDAgAADAAAAAQAAAACAAAA" +
            "DAIAAAAAAAD/////AAAAAP////8AAAAASgIAABAAAAAEAAAAAgAAAAwCAAAAAAAA/////wAAAAD/////" +
            "AAAAAFACAAAUAAAABAAAAAIAAAAMAgAAAAAAAP////8AAAAA/////wAAAABaAgAAGAAAAAgAAAAAAAAA" +
            "bAIAAAAAAAD/////AAAAAP////8AAAAAQnJpZ2h0bmVzcwBmbG9hdACrq6sAAAMAAQABAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAMCAABDb250cmFzdABHcmF5c2NhbGUASW52ZXJ0AEdhbW1hAFRocmVzaG9s" +
            "ZABQYWRkaW5nAGZsb2F0MgCrq6sBAAMAAQACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGICAABNaWNy" +
            "b3NvZnQgKFIpIEhMU0wgU2hhZGVyIENvbXBpbGVyIDEwLjEASVNHTggAAAAAAAAACAAAAE9TR04IAAAA" +
            "AAAAAAgAAABTSEVYcAQAAFAABQAcAQAAaggAAVkAAARGjiAAAAAAAAIAAABYGAAEAHAQAAAAAABVVQAA" +
            "nBgABADgEQAAAAAAVVUAAF8AAAIyAAIAaAAAAgMAAACbAAAEEAAAABAAAAABAAAAPRAAicIAAIBDVRUA" +
            "MgAQAAAAAAABQAAAAAAAAEbuEQAAAAAAUAAABjIAEAAAAAAARgACAEYAEAAAAAAAPAAABxIAEAAAAAAA" +
            "GgAQAAAAAAAKABAAAAAAAB8ABAMKABAAAAAAAD4AAAEVAAABNgAABDIAEAAAAAAARgACADYAAAjCABAA" +
            "AAAAAAJAAAAAAAAAAAAAAAAAAAAAAAAALQAAicIAAIBDVRUA8gAQAAAAAABGDhAAAAAAAEZ+EAAAAAAA" +
            "MQAACzIAEAABAAAAAkAAAAAAAD8AAAA/AAAAAAAAAADmiiAAAAAAAAAAAAAQAAAKQgAQAAEAAABGAhAA" +
            "AAAAAAJAAADQs1k+WRc3P5jdkz0AAAAANwAACdIAEAABAAAABgAQAAEAAACmChAAAQAAAAYJEAAAAAAA" +
            "AAAACtIAEAABAAAABg4QAAEAAAACQAAAAAAAvwAAAAAAAAC/AAAAvzIAAAvSABAAAQAAAAYOEAABAAAA" +
            "VoUgAAAAAAAAAAAABoAgAAAAAAAAAAAAAAAACtIAEAABAAAABg4QAAEAAAACQAAAAAAAPwAAAAAAAAA/" +
            "AAAAPwAAAAtyABAAAgAAAIYDEIBBAAAAAQAAAAJAAAAAAIA/AACAPwAAgD8AAAAANwAACXIAEAABAAAA" +
            "VgUQAAEAAABGAhAAAgAAAIYDEAABAAAAMQAACIIAEAABAAAAAUAAAArXIzwKgCAAAAAAAAEAAAAAAAAI" +
            "EgAQAAIAAAAKgCAAAAAAAAEAAAABQAAAAACAvzEAAAgSABAAAgAAAAFAAABvEoM6CgAQgIEAAAACAAAA" +
            "AQAAB4IAEAABAAAAOgAQAAEAAAAKABAAAgAAADQAAApyABAAAgAAAEYCEAABAAAAAkAAAKzFJzesxSc3" +
            "rMUnNwAAAAAOAAALggAQAAIAAAACQAAAAACAPwAAgD8AAIA/AACAPwqAIAAAAAAAAQAAAC8AAAVyABAA" +
            "AgAAAEYCEAACAAAAOAAAB3IAEAACAAAARgIQAAIAAAD2DxAAAgAAABkAAAVyABAAAgAAAEYCEAACAAAA" +
            "NwAACXIAEAABAAAA9g8QAAEAAABGAhAAAgAAAEYCEAABAAAAHQAACIIAEAABAAAAGoAgAAAAAAABAAAA" +
            "AUAAAAAAAAAQAAAKEgAQAAIAAABGAhAAAQAAAAJAAADQs1k+WRc3P5jdkz0AAAAAHQAACBIAEAACAAAA" +
            "CgAQAAIAAAAagCAAAAAAAAEAAAABAAAHEgAQAAIAAAAKABAAAgAAAAFAAAAAAIA/NyAACXIAEAAAAAAA" +
            "9g8QAAEAAAAGABAAAgAAAEYCEAABAAAANiAABYIAEAAAAAAAOgAQAAAAAACkAAAG8uARAAAAAABGBQIA" +
            "Rg4QAAAAAAA+AAABU1RBVJQAAAAjAAAAAwAAAAAAAAABAAAAEQAAAAAAAAAEAAAAAgAAAAEAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAwAAAAQAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAA"
        );

        /// <summary>
        /// CS 5.0 Separable 1D Gaussian Blur (Horizontal pass using 128-thread groupshared LDS apron).
        /// </summary>
        public static byte[] CsBlurHorizontalBytecode { get; } = Convert.FromBase64String(
            "RFhCQy3lV9GPfdpV+h+e2VNr2NcBAAAAiA0AAAUAAAA0AAAA7AIAAPwCAAAMAwAA7AwAAFJERUawAgAA" +
            "AQAAAMAAAAADAAAAPAAAAAAFU0MAgQAAiAIAAFJEMTE8AAAAGAAAACAAAAAoAAAAJAAAAAwAAAAAAAAA" +
            "nAAAAAIAAAAFAAAABAAAAP////8AAAAAAQAAAA0AAACnAAAABAAAAAUAAAAEAAAA/////wAAAAABAAAA" +
            "DQAAALMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAABAAAAQmx1cklucHV0SABCbHVyT3V0cHV0SABC" +
            "bHVyUGFyYW1zSACrswAAAAUAAADYAAAAMAAAAAAAAAAAAAAAoAEAAAAAAAAEAAAAAgAAALQBAAAAAAAA" +
            "/////wAAAAD/////AAAAANgBAAAEAAAABAAAAAIAAAC0AQAAAAAAAP////8AAAAA/////wAAAADlAQAA" +
            "CAAAAAQAAAACAAAA+AEAAAAAAAD/////AAAAAP////8AAAAAHAIAAAwAAAAEAAAAAAAAACwCAAAAAAAA" +
            "/////wAAAAD/////AAAAAFACAAAQAAAAIAAAAAIAAABkAgAAAAAAAP////8AAAAA/////wAAAABJbWFn" +
            "ZVdpZHRoSABkd29yZACrqwAAEwABAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAArAEAAEltYWdlSGVp" +
            "Z2h0SABCbHVyUmFkaXVzSABpbnQAq6urAAACAAEAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADxAQAA" +
            "Qmx1clBhZEgAZmxvYXQAqwAAAwABAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJQIAAEJsdXJXZWln" +
            "aHRzSABmbG9hdDQAAQADAAEABAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABdAgAATWljcm9zb2Z0IChS" +
            "KSBITFNMIFNoYWRlciBDb21waWxlciAxMC4xAElTR04IAAAAAAAAAAgAAABPU0dOCAAAAAAAAAAIAAAA" +
            "U0hFWNgJAABQAAUAdgIAAGoIAAFZAAAERo4gAAAAAAADAAAAWBgABABwEAAAAAAAVVUAAJwYAAQA4BEA" +
            "AAAAAFVVAABfAAACMhACAF8AAAISIAIAaAAAAgYAAACgAAAFAPARAAAAAAAQAAAAjgAAAJsAAASAAAAA" +
            "AQAAAAEAAAAhAAAHEgAQAAAAAAAaEAIAGoAgAAAAAAAAAAAAHwAEAwoAEAAAAAAAPgAAARUAAAEkAAAI" +
            "EgAQAAAAAAAqgCAAAAAAAAAAAAABQAAAAQAAACUAAAcSABAAAAAAAAoAEAAAAAAAAUAAAAcAAAAjAAAH" +
            "EgAQAAEAAAAKEAIAAUAAAIAAAAAKIAIAHgAABiIAEAAAAAAACgAQAAAAAAAKIAIAHgAACEIAEAAAAAAA" +
            "CoAgAAAAAAAAAAAAAUAAAP////8lAAAHIgAQAAIAAAAqABAAAAAAAAoAEAABAAAANgAABEIAEAACAAAA" +
            "GhACADYAAAWCABAAAgAAAAFAAAAAAAAALQAAicIAAIBDVRUA8gAQAAMAAACWDxAAAgAAAEZ+EAAAAAAA" +
            "qAAACfLwEQAAAAAAGgAQAAAAAAABQAAAAAAAAEYOEAADAAAAIgAABoIAEAAAAAAACiACAAoAEAAAAAAA" +
            "HwAEAzoAEAAAAAAAKQAABoIAEAAAAAAAChACAAFAAAAHAAAAHgAACCIAEAACAAAACgAQgEEAAAAAAAAA" +
            "OgAQAAAAAAAeAAAGIgAQAAIAAAAaABAAAgAAAAogAgAkAAAHIgAQAAIAAAAaABAAAgAAAAFAAAAAAAAA" +
            "JQAABxIAEAACAAAAKgAQAAAAAAAaABAAAgAAAC0AAInCAACAQ1UVAPIAEAADAAAAhg8QAAIAAABGfhAA" +
            "AAAAAKgAAAjy8BEAAAAAAAogAgABQAAAAAAAAEYOEAADAAAAHgAAB4IAEAAAAAAAOgAQAAAAAAABQAAA" +
            "gAAAAB4AAAaCABAAAAAAADoAEAAAAAAACiACAB4AAAcSABAAAgAAAAoAEAAAAAAAAUAAAIAAAAAeAAAG" +
            "EgAQAAIAAAAKABAAAgAAAAogAgAlAAAHEgAQAAMAAAAqABAAAAAAADoAEAAAAAAANgAABeIAEAADAAAA" +
            "pg8QAAIAAAAtAACJwgAAgENVFQDyABAAAwAAAEYOEAADAAAARn4QAAAAAACoAAAJ8vARAAAAAAAKABAA" +
            "AgAAAAFAAAAAAAAARg4QAAMAAAAVAAABvhgAASIAAAhCABAAAAAAAAoAEAABAAAACoAgAAAAAAAAAAAA" +
            "HwAEAyoAEAAAAAAApwAACfIAEAACAAAAGgAQAAAAAAABQAAAAAAAAEb+EQAAAAAAHgAACsIAEAAAAAAA" +
            "VgUQAAAAAAACQAAAAAAAAAAAAAD/////AQAAAKcAAAnyABAAAwAAACoAEAAAAAAAAUAAAAAAAABG/hEA" +
            "AAAAAKcAAAnyABAABAAAADoAEAAAAAAAAUAAAAAAAABG/hEAAAAAAAAAAAfyABAAAwAAAEYOEAADAAAA" +
            "Rg4QAAQAAAA4AAAI8gAQAAMAAABGDhAAAwAAAFaFIAAAAAAAAQAAADIAAAryABAAAgAAAEYOEAACAAAA" +
            "BoAgAAAAAAABAAAARg4QAAMAAAAhAAAK8gAQAAMAAAAGABAAAAAAAAJAAAACAAAAAwAAAAQAAAAFAAAA" +
            "HwAEAwoAEAADAAAAHgAACsIAEAAAAAAAVgUQAAAAAAACQAAAAAAAAAAAAAD+////AgAAAKcAAAnyABAA" +
            "BAAAACoAEAAAAAAAAUAAAAAAAABG/hEAAAAAAKcAAAnyABAABQAAADoAEAAAAAAAAUAAAAAAAABG/hEA" +
            "AAAAAAAAAAfyABAABAAAAEYOEAAEAAAARg4QAAUAAAAyAAAK8gAQAAIAAABGDhAABAAAAKaKIAAAAAAA" +
            "AQAAAEYOEAACAAAAFQAAAR8ABAMaABAAAwAAAB4AAArCABAAAAAAAFYFEAAAAAAAAkAAAAAAAAAAAAAA" +
            "/f///wMAAACnAAAJ8gAQAAQAAAAqABAAAAAAAAFAAAAAAAAARv4RAAAAAACnAAAJ8gAQAAUAAAA6ABAA" +
            "AAAAAAFAAAAAAAAARv4RAAAAAAAAAAAH8gAQAAQAAABGDhAABAAAAEYOEAAFAAAAMgAACvIAEAACAAAA" +
            "Rg4QAAQAAAD2jyAAAAAAAAEAAABGDhAAAgAAABUAAAEfAAQDKgAQAAMAAAAeAAAKwgAQAAAAAABWBRAA" +
            "AAAAAAJAAAAAAAAAAAAAAPz///8EAAAApwAACfIAEAAEAAAAKgAQAAAAAAABQAAAAAAAAEb+EQAAAAAA" +
            "pwAACfIAEAAFAAAAOgAQAAAAAAABQAAAAAAAAEb+EQAAAAAAAAAAB/IAEAAEAAAARg4QAAQAAABGDhAA" +
            "BQAAADIAAAryABAAAgAAAEYOEAAEAAAABoAgAAAAAAACAAAARg4QAAIAAAAVAAABHwAEAzoAEAADAAAA" +
            "HgAACsIAEAAAAAAAVgUQAAAAAAACQAAAAAAAAAAAAAD7////BQAAAKcAAAnyABAAAwAAACoAEAAAAAAA" +
            "AUAAAAAAAABG/hEAAAAAAKcAAAnyABAABAAAADoAEAAAAAAAAUAAAAAAAABG/hEAAAAAAAAAAAfyABAA" +
            "AwAAAEYOEAADAAAARg4QAAQAAAAyAAAK8gAQAAIAAABGDhAAAwAAAFaFIAAAAAAAAgAAAEYOEAACAAAA" +
            "FQAAASEAAApSABAAAAAAAAYAEAAAAAAAAkAAAAYAAAAAAAAABwAAAAAAAAAfAAQDCgAQAAAAAAAeAAAK" +
            "kgAQAAAAAABWBRAAAAAAAAJAAAD6////AAAAAAAAAAAGAAAApwAACfIAEAADAAAACgAQAAAAAAABQAAA" +
            "AAAAAEb+EQAAAAAApwAACfIAEAAEAAAAOgAQAAAAAAABQAAAAAAAAEb+EQAAAAAAAAAAB/IAEAADAAAA" +
            "Rg4QAAMAAABGDhAABAAAADIAAAryABAAAgAAAEYOEAADAAAApoogAAAAAAACAAAARg4QAAIAAAAVAAAB" +
            "HwAEAyoAEAAAAAAAHgAACjIAEAAAAAAAVgUQAAAAAAACQAAA+f///wcAAAAAAAAAAAAAAKcAAAnyABAA" +
            "AwAAAAoAEAAAAAAAAUAAAAAAAABG/hEAAAAAAKcAAAnyABAAAAAAABoAEAAAAAAAAUAAAAAAAABG/hEA" +
            "AAAAAAAAAAfyABAAAAAAAEYOEAAAAAAARg4QAAMAAAAyAAAK8gAQAAIAAABGDhAAAAAAAPaPIAAAAAAA" +
            "AgAAAEYOEAACAAAAFQAAATYAAATiABAAAQAAAFYVAgCkAAAH8uARAAAAAABGDhAAAQAAAEYOEAACAAAA" +
            "FQAAAT4AAAFTVEFUlAAAAFoAAAAGAAAAAAAAAAIAAAAPAAAAHAAAAAAAAAACAAAACQAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAMAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAEAAAA="
        );

        /// <summary>
        /// CS 5.0 Separable 1D Gaussian Blur (Vertical pass using 128-thread groupshared LDS apron).
        /// </summary>
        public static byte[] CsBlurVerticalBytecode { get; } = Convert.FromBase64String(
            "RFhCQ5gpRemqFM7nhjJB8bgfrnsBAAAAlA0AAAUAAAA0AAAA7AIAAPwCAAAMAwAA+AwAAFJERUawAgAA" +
            "AQAAAMAAAAADAAAAPAAAAAAFU0MAgQAAiAIAAFJEMTE8AAAAGAAAACAAAAAoAAAAJAAAAAwAAAAAAAAA" +
            "nAAAAAIAAAAFAAAABAAAAP////8AAAAAAQAAAA0AAACnAAAABAAAAAUAAAAEAAAA/////wAAAAABAAAA" +
            "DQAAALMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAABAAAAQmx1cklucHV0VgBCbHVyT3V0cHV0VgBC" +
            "bHVyUGFyYW1zVgCrswAAAAUAAADYAAAAMAAAAAAAAAAAAAAAoAEAAAAAAAAEAAAAAgAAALQBAAAAAAAA" +
            "/////wAAAAD/////AAAAANgBAAAEAAAABAAAAAIAAAC0AQAAAAAAAP////8AAAAA/////wAAAADlAQAA" +
            "CAAAAAQAAAACAAAA+AEAAAAAAAD/////AAAAAP////8AAAAAHAIAAAwAAAAEAAAAAAAAACwCAAAAAAAA" +
            "/////wAAAAD/////AAAAAFACAAAQAAAAIAAAAAIAAABkAgAAAAAAAP////8AAAAA/////wAAAABJbWFn" +
            "ZVdpZHRoVgBkd29yZACrqwAAEwABAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAArAEAAEltYWdlSGVp" +
            "Z2h0VgBCbHVyUmFkaXVzVgBpbnQAq6urAAACAAEAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADxAQAA" +
            "Qmx1clBhZFYAZmxvYXQAqwAAAwABAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJQIAAEJsdXJXZWln" +
            "aHRzVgBmbG9hdDQAAQADAAEABAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABdAgAATWljcm9zb2Z0IChS" +
            "KSBITFNMIFNoYWRlciBDb21waWxlciAxMC4xAElTR04IAAAAAAAAAAgAAABPU0dOCAAAAAAAAAAIAAAA" +
            "U0hFWOQJAABQAAUAeQIAAGoIAAFZAAAERo4gAAAAAAADAAAAWBgABABwEAAAAAAAVVUAAJwYAAQA4BEA" +
            "AAAAAFVVAABfAAACMhACAF8AAAIiIAIAaAAAAgYAAACgAAAFAPARAAAAAAAQAAAAjgAAAJsAAAQBAAAA" +
            "gAAAAAEAAAAhAAAHEgAQAAAAAAAKEAIACoAgAAAAAAAAAAAAHwAEAwoAEAAAAAAAPgAAARUAAAEkAAAI" +
            "EgAQAAAAAAAqgCAAAAAAAAAAAAABQAAAAQAAACUAAAcSABAAAAAAAAoAEAAAAAAAAUAAAAcAAAAjAAAK" +
            "4gAQAAEAAABWFQIAAkAAAAAAAACAAAAAgAAAAIAAAABWJQIAHgAABiIAEAAAAAAACgAQAAAAAAAaIAIA" +
            "HgAACEIAEAAAAAAAGoAgAAAAAAAAAAAAAUAAAP////8lAAAHEgAQAAIAAAAqABAAAAAAADoAEAABAAAA" +
            "NgAABCIAEAACAAAAChACADYAAAVCABAAAgAAAAFAAAAAAAAALQAAicIAAIBDVRUA8gAQAAMAAAAWChAA" +
            "AgAAAEZ+EAAAAAAAqAAACfLwEQAAAAAAGgAQAAAAAAABQAAAAAAAAEYOEAADAAAAIgAABoIAEAAAAAAA" +
            "GiACAAoAEAAAAAAAHwAEAzoAEAAAAAAAKQAABoIAEAAAAAAAGhACAAFAAAAHAAAAHgAACBIAEAACAAAA" +
            "CgAQgEEAAAAAAAAAOgAQAAAAAAAeAAAGEgAQAAIAAAAKABAAAgAAABogAgAkAAAHEgAQAAIAAAAKABAA" +
            "AgAAAAFAAAAAAAAAJQAAB4IAEAACAAAAKgAQAAAAAAAKABAAAgAAAC0AAInCAACAQ1UVAPIAEAADAAAA" +
            "1goQAAIAAABGfhAAAAAAAKgAAAjy8BEAAAAAABogAgABQAAAAAAAAEYOEAADAAAAHgAAB4IAEAAAAAAA" +
            "OgAQAAAAAAABQAAAgAAAAB4AAAaCABAAAAAAADoAEAAAAAAAGiACAB4AAAcSABAAAgAAAAoAEAAAAAAA" +
            "AUAAAIAAAAAeAAAGEgAQAAIAAAAKABAAAgAAABogAgAlAAAHIgAQAAMAAAAqABAAAAAAADoAEAAAAAAA" +
            "NgAABdIAEAADAAAAVgoQAAIAAAAtAACJwgAAgENVFQDyABAAAwAAAEYOEAADAAAARn4QAAAAAACoAAAJ" +
            "8vARAAAAAAAKABAAAgAAAAFAAAAAAAAARg4QAAMAAAAVAAABvhgAASIAAAhCABAAAAAAADoAEAABAAAA" +
            "GoAgAAAAAAAAAAAAHwAEAyoAEAAAAAAApwAACfIAEAACAAAAGgAQAAAAAAABQAAAAAAAAEb+EQAAAAAA" +
            "HgAACsIAEAAAAAAAVgUQAAAAAAACQAAAAAAAAAAAAAD/////AQAAAKcAAAnyABAAAwAAACoAEAAAAAAA" +
            "AUAAAAAAAABG/hEAAAAAAKcAAAnyABAABAAAADoAEAAAAAAAAUAAAAAAAABG/hEAAAAAAAAAAAfyABAA" +
            "AwAAAEYOEAADAAAARg4QAAQAAAA4AAAI8gAQAAMAAABGDhAAAwAAAFaFIAAAAAAAAQAAADIAAAryABAA" +
            "AgAAAEYOEAACAAAABoAgAAAAAAABAAAARg4QAAMAAAAhAAAK8gAQAAMAAAAGABAAAAAAAAJAAAACAAAA" +
            "AwAAAAQAAAAFAAAAHwAEAwoAEAADAAAAHgAACsIAEAAAAAAAVgUQAAAAAAACQAAAAAAAAAAAAAD+////" +
            "AgAAAKcAAAnyABAABAAAACoAEAAAAAAAAUAAAAAAAABG/hEAAAAAAKcAAAnyABAABQAAADoAEAAAAAAA" +
            "AUAAAAAAAABG/hEAAAAAAAAAAAfyABAABAAAAEYOEAAEAAAARg4QAAUAAAAyAAAK8gAQAAIAAABGDhAA" +
            "BAAAAKaKIAAAAAAAAQAAAEYOEAACAAAAFQAAAR8ABAMaABAAAwAAAB4AAArCABAAAAAAAFYFEAAAAAAA" +
            "AkAAAAAAAAAAAAAA/f///wMAAACnAAAJ8gAQAAQAAAAqABAAAAAAAAFAAAAAAAAARv4RAAAAAACnAAAJ" +
            "8gAQAAUAAAA6ABAAAAAAAAFAAAAAAAAARv4RAAAAAAAAAAAH8gAQAAQAAABGDhAABAAAAEYOEAAFAAAA" +
            "MgAACvIAEAACAAAARg4QAAQAAAD2jyAAAAAAAAEAAABGDhAAAgAAABUAAAEfAAQDKgAQAAMAAAAeAAAK" +
            "wgAQAAAAAABWBRAAAAAAAAJAAAAAAAAAAAAAAPz///8EAAAApwAACfIAEAAEAAAAKgAQAAAAAAABQAAA" +
            "AAAAAEb+EQAAAAAApwAACfIAEAAFAAAAOgAQAAAAAAABQAAAAAAAAEb+EQAAAAAAAAAAB/IAEAAEAAAA" +
            "Rg4QAAQAAABGDhAABQAAADIAAAryABAAAgAAAEYOEAAEAAAABoAgAAAAAAACAAAARg4QAAIAAAAVAAAB" +
            "HwAEAzoAEAADAAAAHgAACsIAEAAAAAAAVgUQAAAAAAACQAAAAAAAAAAAAAD7////BQAAAKcAAAnyABAA" +
            "AwAAACoAEAAAAAAAAUAAAAAAAABG/hEAAAAAAKcAAAnyABAABAAAADoAEAAAAAAAAUAAAAAAAABG/hEA" +
            "AAAAAAAAAAfyABAAAwAAAEYOEAADAAAARg4QAAQAAAAyAAAK8gAQAAIAAABGDhAAAwAAAFaFIAAAAAAA" +
            "AgAAAEYOEAACAAAAFQAAASEAAApSABAAAAAAAAYAEAAAAAAAAkAAAAYAAAAAAAAABwAAAAAAAAAfAAQD" +
            "CgAQAAAAAAAeAAAKkgAQAAAAAABWBRAAAAAAAAJAAAD6////AAAAAAAAAAAGAAAApwAACfIAEAADAAAA" +
            "CgAQAAAAAAABQAAAAAAAAEb+EQAAAAAApwAACfIAEAAEAAAAOgAQAAAAAAABQAAAAAAAAEb+EQAAAAAA" +
            "AAAAB/IAEAADAAAARg4QAAMAAABGDhAABAAAADIAAAryABAAAgAAAEYOEAADAAAApoogAAAAAAACAAAA" +
            "Rg4QAAIAAAAVAAABHwAEAyoAEAAAAAAAHgAACjIAEAAAAAAAVgUQAAAAAAACQAAA+f///wcAAAAAAAAA" +
            "AAAAAKcAAAnyABAAAwAAAAoAEAAAAAAAAUAAAAAAAABG/hEAAAAAAKcAAAnyABAAAAAAABoAEAAAAAAA" +
            "AUAAAAAAAABG/hEAAAAAAAAAAAfyABAAAAAAAEYOEAAAAAAARg4QAAMAAAAyAAAK8gAQAAIAAABGDhAA" +
            "AAAAAPaPIAAAAAAAAgAAAEYOEAACAAAAFQAAATYAAAQSABAAAQAAAAoQAgCkAAAH8uARAAAAAABGDhAA" +
            "AQAAAEYOEAACAAAAFQAAAT4AAAFTVEFUlAAAAFoAAAAGAAAAAAAAAAIAAAAPAAAAHAAAAAAAAAACAAAA" +
            "CQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAEAAAA="
        );

        /// <summary>
        /// CS 5.0 3x3 Convolution (Sobel Edge & Laplacian Sharpening with 18x18 LDS Apron).
        /// </summary>
        public static byte[] CsConvolution3x3Bytecode { get; } = Convert.FromBase64String(
            "RFhCQ6+JAB2f02pnZ4zdmP3U8YABAAAAIBIAAAUAAAA0AAAAWAIAAGgCAAB4AgAAhBEAAFJERUYcAgAA" +
            "AQAAALwAAAADAAAAPAAAAAAFU0MAgQAA9AEAAFJEMTE8AAAAGAAAACAAAAAoAAAAJAAAAAwAAAAAAAAA" +
            "nAAAAAIAAAAFAAAABAAAAP////8AAAAAAQAAAA0AAACmAAAABAAAAAUAAAAEAAAA/////wAAAAABAAAA" +
            "DQAAALEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAABAAAAQ29udklucHV0AENvbnZPdXRwdXQAQ29u" +
            "dlBhcmFtcwCxAAAABAAAANQAAAAQAAAAAAAAAAAAAAB0AQAAAAAAAAQAAAACAAAAhAEAAAAAAAD/////" +
            "AAAAAP////8AAAAAqAEAAAQAAAAEAAAAAgAAAIQBAAAAAAAA/////wAAAAD/////AAAAALMBAAAIAAAA" +
            "BAAAAAIAAACEAQAAAAAAAP////8AAAAA/////wAAAAC8AQAADAAAAAQAAAACAAAA0AEAAAAAAAD/////" +
            "AAAAAP////8AAAAAQ29udldpZHRoAGR3b3JkAAAAEwABAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "fgEAAENvbnZIZWlnaHQAQ29udk1vZGUAQ29udlN0cmVuZ3RoAGZsb2F0AKsAAAMAAQABAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAMkBAABNaWNyb3NvZnQgKFIpIEhMU0wgU2hhZGVyIENvbXBpbGVyIDEwLjEA" +
            "SVNHTggAAAAAAAAACAAAAE9TR04IAAAAAAAAAAgAAABTSEVYBA8AAFAABQDBAwAAaggAAVkAAARGjiAA" +
            "AAAAAAEAAABYGAAEAHAQAAAAAABVVQAAnBgABADgEQAAAAAAVVUAAF8AAAIyEAIAXwAAAjIgAgBoAAAC" +
            "BgAAAKAAAAUA8BEAAAAAACABAAASAAAAmwAABBAAAAAQAAAAAQAAACMAAAryABAAAAAAAEYVAgACQAAA" +
            "EAAAABAAAAAQAAAAEAAAAEYlAgAeAAALMgAQAAEAAABGgCAAAAAAAAAAAAACQAAA//////////8AAAAA" +
            "AAAAAB4AAAZCABAAAQAAABogAgABQAAAAQAAACkAAAaCABAAAQAAAAogAgABQAAABAAAAB4AAAcSABAA" +
            "AgAAADoAEAABAAAAAUAAABAAAAAlAAAHYgAQAAMAAAAGAxAAAAAAAAYBEAABAAAANgAABYIAEAADAAAA" +
            "AUAAAAAAAAAtAACJwgAAgENVFQDyABAABAAAAJYPEAADAAAARn4QAAAAAACoAAAJ8vARAAAAAAAqABAA" +
            "AQAAAAoAEAACAAAARg4QAAQAAAAgAAAJ8gAQAAQAAAAGJQIAAkAAAAAAAAAPAAAAAAAAAA8AAAAfAAAC" +
            "CiACAB4AAAciABAAAgAAAAoAEAAAAAAAAUAAAP////8kAAAHIgAQAAIAAAAaABAAAgAAAAFAAAAAAAAA" +
            "JQAABxIAEAADAAAACgAQAAEAAAAaABAAAgAAAC0AAInCAACAQ1UVAPIAEAAFAAAAhg8QAAMAAABGfhAA" +
            "AAAAAKgAAAny8BEAAAAAACoAEAABAAAAAUAAAAAAAABGDhAABQAAABUAAAEfAAQDGgAQAAQAAAAeAAAH" +
            "IgAQAAIAAAAKABAAAAAAAAFAAAABAAAAJQAABxIAEAAFAAAACgAQAAEAAAAaABAAAgAAADYAAAXiABAA" +
            "BQAAAKYPEAADAAAALQAAicIAAIBDVRUA8gAQAAUAAABGDhAABQAAAEZ+EAAAAAAAqAAACfLwEQAAAAAA" +
            "KgAQAAEAAAABQAAAEAEAAEYOEAAFAAAAFQAAAR8AAAIaIAIAHgAAByIAEAACAAAAOgAQAAAAAAABQAAA" +
            "/////yQAAAciABAAAgAAABoAEAACAAAAAUAAAAAAAAAlAAAHIgAQAAUAAAAaABAAAQAAABoAEAACAAAA" +
            "NgAABdIAEAAFAAAAVg8QAAMAAAAtAACJwgAAgENVFQDyABAABQAAAEYOEAAFAAAARn4QAAAAAACoAAAJ" +
            "8vARAAAAAAABQAAAAAAAAAoAEAACAAAARg4QAAUAAAAVAAABHwAEAzoAEAAEAAAAHgAAByIAEAACAAAA" +
            "OgAQAAAAAAABQAAAAQAAACUAAAciABAABQAAABoAEAABAAAAGgAQAAIAAAA2AAAF0gAQAAUAAABWDxAA" +
            "AwAAAC0AAInCAACAQ1UVAPIAEAADAAAARg4QAAUAAABGfhAAAAAAAKgAAAny8BEAAAAAAAFAAAARAAAA" +
            "CgAQAAIAAABGDhAAAwAAABUAAAEBAAAH8gAQAAMAAACmDxAABAAAAEYEEAAEAAAAHwAEAwoAEAADAAAA" +
            "HgAACmIAEAACAAAABgMQAAAAAAACQAAAAAAAAP//////////AAAAACQAAApiABAAAgAAAFYGEAACAAAA" +
            "AkAAAAAAAAAAAAAAAAAAAAAAAAAlAAAHMgAQAAQAAABGABAAAQAAAJYFEAACAAAANgAACMIAEAAEAAAA" +
            "AkAAAAAAAAAAAAAAAAAAAAAAAAAtAACJwgAAgENVFQDiABAAAgAAAEYOEAAEAAAANnkQAAAAAACoAAAJ" +
            "cvARAAAAAAABQAAAAAAAAAFAAAAAAAAAlgcQAAIAAAAVAAABHwAEAxoAEAADAAAAHgAACmIAEAACAAAA" +
            "BgMQAAAAAAACQAAAAAAAAAEAAAD/////AAAAACUAAAcSABAABAAAAAoAEAABAAAAGgAQAAIAAAAkAAAH" +
            "IgAQAAIAAAAqABAAAgAAAAFAAAAAAAAAJQAAByIAEAAEAAAAGgAQAAEAAAAaABAAAgAAADYAAAjCABAA" +
            "BAAAAAJAAAAAAAAAAAAAAAAAAAAAAAAALQAAicIAAIBDVRUA4gAQAAIAAABGDhAABAAAADZ5EAAAAAAA" +
            "qAAACXLwEQAAAAAAAUAAAAAAAAABQAAAEAEAAJYHEAACAAAAFQAAAR8ABAMqABAAAwAAAB4AAApiABAA" +
            "AgAAAAYDEAAAAAAAAkAAAAAAAAD/////AQAAAAAAAAAkAAAHIgAQAAIAAAAaABAAAgAAAAFAAAAAAAAA" +
            "JQAABzIAEAAEAAAARgAQAAEAAACWBRAAAgAAADYAAAjCABAABAAAAAJAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "LQAAicIAAIBDVRUA4gAQAAIAAABGDhAABAAAADZ5EAAAAAAAqAAACXLwEQAAAAAAAUAAABEAAAABQAAA" +
            "AAAAAJYHEAACAAAAFQAAAR8ABAM6ABAAAwAAAB4AAApiABAAAgAAAAYDEAAAAAAAAkAAAAAAAAABAAAA" +
            "AQAAAAAAAAAlAAAHMgAQAAMAAABGABAAAQAAAJYFEAACAAAANgAACMIAEAADAAAAAkAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAtAACJwgAAgENVFQDiABAAAgAAAEYOEAADAAAANnkQAAAAAACoAAAJcvARAAAAAAABQAAA" +
            "EQAAAAFAAAAQAQAAlgcQAAIAAAAVAAABvhgAASIAAAgyABAAAQAAAMYAEAAAAAAARoAgAAAAAAAAAAAA" +
            "AQAABxIAEAABAAAAGgAQAAEAAAAKABAAAQAAAB8ABAMKABAAAQAAAB4AAAYSABAAAQAAAAogAgABQAAA" +
            "AQAAAKcAAAnyABAAAwAAACoAEAABAAAACgAQAAIAAABG/hEAAAAAAB8AAAQqgCAAAAAAAAAAAAApAAAH" +
            "IgAQAAEAAAAKABAAAQAAAAFAAAAEAAAAHgAAByIAEAABAAAAGgAQAAEAAAABQAAA8P///6cAAAjiABAA" +
            "AgAAABogAgAaABAAAQAAAAb5EQAAAAAAEAAACiIAEAACAAAAlgcQAAIAAAACQAAA0LNZPlkXNz+Y3ZM9" +
            "AAAAAKcAAAhyABAABAAAABogAgAKABAAAgAAAEbyEQAAAAAAEAAACkIAEAACAAAARgIQAAQAAAACQAAA" +
            "0LNZPlkXNz+Y3ZM9AAAAAB4AAAeCABAAAgAAADoAEAABAAAAAUAAACAAAACnAAAIcgAQAAQAAAAaIAIA" +
            "OgAQAAIAAABG8hEAAAAAABAAAAoSABAABAAAAEYCEAAEAAAAAkAAANCzWT5ZFzc/mN2TPQAAAACnAAAJ" +
            "4gAQAAQAAAAqABAAAQAAABoAEAABAAAABvkRAAAAAAAQAAAKIgAQAAQAAACWBxAABAAAAAJAAADQs1k+" +
            "WRc3P5jdkz0AAAAApwAACXIAEAAFAAAAKgAQAAEAAAA6ABAAAgAAAEbyEQAAAAAAEAAACkIAEAAEAAAA" +
            "RgIQAAUAAAACQAAA0LNZPlkXNz+Y3ZM9AAAAAB4AAAaCABAABAAAABogAgABQAAAAgAAAKcAAAlyABAA" +
            "BQAAADoAEAAEAAAAGgAQAAEAAABG8hEAAAAAABAAAAoiABAAAQAAAEYCEAAFAAAAAkAAANCzWT5ZFzc/" +
            "mN2TPQAAAACnAAAJcgAQAAUAAAA6ABAABAAAAAoAEAACAAAARvIRAAAAAAAQAAAKEgAQAAUAAABGAhAA" +
            "BQAAAAJAAADQs1k+WRc3P5jdkz0AAAAApwAACeIAEAAFAAAAOgAQAAQAAAA6ABAAAgAAAAb5EQAAAAAA" +
            "EAAACoIAEAACAAAAlgcQAAUAAAACQAAA0LNZPlkXNz+Y3ZM9AAAAAAAAAAiCABAABAAAABoAEIBBAAAA" +
            "AgAAAAoAEAAEAAAAAAAACCIAEAAEAAAAKgAQAAQAAAAaABCAQQAAAAQAAAAyAAAJIgAQAAQAAAAaABAA" +
            "BAAAAAFAAAAAAABAOgAQAAQAAAAAAAAIQgAQAAQAAAAaABCAQQAAAAEAAAA6ABAAAgAAAAAAAAciABAA" +
            "BAAAACoAEAAEAAAAGgAQAAQAAAAyAAALIgAQAAIAAAAqABCAQQAAAAIAAAABQAAAAAAAQBoAEIBBAAAA" +
            "AgAAAAAAAAgiABAAAgAAAAoAEIBBAAAABAAAABoAEAACAAAAMgAACSIAEAABAAAACgAQAAUAAAABQAAA" +
            "AAAAQBoAEAABAAAAAAAAByIAEAABAAAAOgAQAAIAAAAaABAAAQAAAAAAAAciABAAAQAAABoAEAABAAAA" +
            "GgAQAAIAAAA4AAAHIgAQAAEAAAAaABAAAQAAABoAEAABAAAAMgAACSIAEAABAAAAGgAQAAQAAAAaABAA" +
            "BAAAABoAEAABAAAASwAABSIAEAABAAAAGgAQAAEAAAA4AAAIIgAQAAEAAAAaABAAAQAAADqAIAAAAAAA" +
            "AAAAADYgAAVyABAAAwAAAFYFEAABAAAAEgAAAacAAAjyABAABAAAABogAgAKABAAAgAAAEb+EQAAAAAA" +
            "HgAABiIAEAABAAAAGiACAAFAAAACAAAApwAACfIAEAACAAAAGgAQAAEAAAAKABAAAgAAAEb+EQAAAAAA" +
            "KQAABxIAEAABAAAACgAQAAEAAAABQAAABAAAAB4AAAcSABAAAQAAAAoAEAABAAAAAUAAAPD///+nAAAJ" +
            "8gAQAAUAAAAqABAAAQAAAAoAEAABAAAARv4RAAAAAAAeAAAHEgAQAAEAAAA6ABAAAQAAAAFAAAAgAAAA" +
            "pwAACfIAEAABAAAAKgAQAAEAAAAKABAAAQAAAEb+EQAAAAAAAAAAB/IAEAACAAAARg4QAAIAAABGDhAA" +
            "BAAAAAAAAAfyABAAAgAAAEYOEAAFAAAARg4QAAIAAAAAAAAH8gAQAAEAAABGDhAAAQAAAEYOEAACAAAA" +
            "MgAADfIAEAABAAAARg4QAAMAAAACQAAAAACgQAAAoEAAAKBAAACgQEYOEIBBAAAAAQAAAAAAAAjyABAA" +
            "AQAAAEYOEIBBAAAAAwAAAEYOEAABAAAAMiAACvIAEAADAAAA9o8gAAAAAAAAAAAARg4QAAEAAABGDhAA" +
            "AwAAABUAAAGkAAAH8uARAAAAAABGDhAAAAAAAEYOEAADAAAAFQAAAT4AAAFTVEFUlAAAAIUAAAAGAAAA" +
            "AAAAAAIAAAAcAAAAJwAAAAIAAAADAAAACQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAkAAAAAAAAA" +
            "AAAAAAAAAAAJAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAABAAAAAAAAAAEAAAA="
        );
    }
}