using System;

namespace ZeroGraphics.Imaging.Gpu.Shaders
{
    /// <summary>
    /// Precompiled Direct3D 11 HLSL Shader Bytecodes (Shader Model 4.0).
    /// Embedded as Base64 strings to eliminate runtime shader compiler (fxc / d3dcompiler_47) dependencies.
    /// </summary>
    public static class GpuImageShaderBytecodes
    {
        /// <summary>
        /// Fullscreen Quad Vertex Shader
        /// </summary>
        public static byte[] VsFullscreenBytecode { get; } = Convert.FromBase64String(
            "RFhCQ9CUna679lqtaly5agkxq6cBAAAAqAIAAAUAAAA0AAAAgAAAALQAAAAMAQAALAIAAFJERUZEAAAA" +
            "AAAAAAAAAAAAAAAAHAAAAAAE/v8AgQAAHAAAAE1pY3Jvc29mdCAoUikgSExTTCBTaGFkZXIgQ29tcGls" +
            "ZXIgMTAuMQBJU0dOLAAAAAEAAAAIAAAAIAAAAAAAAAAGAAAAAQAAAAAAAAABAQAAU1ZfVmVydGV4SUQA" +
            "T1NHTlAAAAACAAAACAAAADgAAAAAAAAAAQAAAAMAAAAAAAAADwAAAEQAAAAAAAAAAAAAAAMAAAABAAAA" +
            "AwwAAFNWX1BPU0lUSU9OAFRFWENPT1JEAKurq1NIRFIYAQAAQAABAEYAAABgAAAEEhAQAAAAAAAGAAAA" +
            "ZwAABPIgEAAAAAAAAQAAAGUAAAMyIBAAAQAAAGgAAAIBAAAAKQAABxIAEAAAAAAAChAQAAAAAAABQAAA" +
            "AQAAAAEAAAcSABAAAAAAAAoAEAAAAAAAAUAAAAIAAAABAAAHQgAQAAAAAAAKEBAAAAAAAAFAAAACAAAA" +
            "VgAABTIAEAAAAAAAhgAQAAAAAAAyAAAPMiAQAAAAAABGABAAAAAAAAJAAAAAAABAAAAAwAAAAAAAAAAA" +
            "AkAAAAAAgL8AAIA/AAAAAAAAAAA2AAAFMiAQAAEAAABGABAAAAAAADYAAAjCIBAAAAAAAAJAAAAAAAAA" +
            "AAAAAAAAAAAAAIA/PgAAAVNUQVR0AAAACAAAAAEAAAAAAAAAAwAAAAEAAAABAAAAAgAAAAEAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAQAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAA="
        );

        /// <summary>
        /// Bilinear / Point Resampling Pixel Shader
        /// </summary>
        public static byte[] PsResizeBytecode { get; } = Convert.FromBase64String(
            "RFhCQ6mwlBoTGTMVOm1LLe291PcBAAAAUAIAAAUAAAA0AAAA3AAAADQBAABoAQAA1AEAAFJERUagAAAA" +
            "AAAAAAAAAAACAAAAHAAAAAAE//8AgQAAeAAAAFwAAAADAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAABAAAA" +
            "awAAAAIAAAAFAAAABAAAAP////8AAAAAAQAAAA0AAABkZWZhdWx0U2FtcGxlcgBpbnB1dFRleHR1cmUA" +
            "TWljcm9zb2Z0IChSKSBITFNMIFNoYWRlciBDb21waWxlciAxMC4xAElTR05QAAAAAgAAAAgAAAA4AAAA" +
            "AAAAAAEAAAADAAAAAAAAAA8AAABEAAAAAAAAAAAAAAADAAAAAQAAAAMDAABTVl9QT1NJVElPTgBURVhD" +
            "T09SRACrq6tPU0dOLAAAAAEAAAAIAAAAIAAAAAAAAAAAAAAAAwAAAAAAAAAPAAAAU1ZfVEFSR0VUAKur" +
            "U0hEUmQAAABAAAAAGQAAAFoAAAMAYBAAAAAAAFgYAAQAcBAAAAAAAFVVAABiEAADMhAQAAEAAABlAAAD" +
            "8iAQAAAAAABFAAAJ8iAQAAAAAABGEBAAAQAAAEZ+EAAAAAAAAGAQAAAAAAA+AAABU1RBVHQAAAACAAAA" +
            "AAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=="
        );

        /// <summary>
        /// Brightness / Contrast / Grayscale Pixel Shader
        /// </summary>
        public static byte[] PsColorAdjustBytecode { get; } = Convert.FromBase64String(
            "RFhCQ/4IyZrpugW7vqA5ObO3L0QBAAAAnAQAAAUAAAA0AAAAuAEAABACAABEAgAAIAQAAFJERUZ8AQAA" +
            "AQAAAKQAAAADAAAAHAAAAAAE//8AgQAAUgEAAHwAAAADAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAABAAAA" +
            "iwAAAAIAAAAFAAAABAAAAP////8AAAAAAQAAAA0AAACYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAA" +
            "AQAAAGRlZmF1bHRTYW1wbGVyAGlucHV0VGV4dHVyZQBDb2xvckJ1ZmZlcgCYAAAABAAAALwAAAAQAAAA" +
            "AAAAAAAAAAAcAQAAAAAAAAQAAAACAAAAKAEAAAAAAAA4AQAABAAAAAQAAAACAAAAKAEAAAAAAABBAQAA" +
            "CAAAAAQAAAACAAAAKAEAAAAAAABLAQAADAAAAAQAAAACAAAAKAEAAAAAAABCcmlnaHRuZXNzAKsAAAMA" +
            "AQABAAAAAAAAAAAAQ29udHJhc3QAR3JheXNjYWxlAEludmVydABNaWNyb3NvZnQgKFIpIEhMU0wgU2hh" +
            "ZGVyIENvbXBpbGVyIDEwLjEAq6tJU0dOUAAAAAIAAAAIAAAAOAAAAAAAAAABAAAAAwAAAAAAAAAPAAAA" +
            "RAAAAAAAAAAAAAAAAwAAAAEAAAADAwAAU1ZfUE9TSVRJT04AVEVYQ09PUkQAq6urT1NHTiwAAAABAAAA" +
            "CAAAACAAAAAAAAAAAAAAAAMAAAAAAAAADwAAAFNWX1RBUkdFVACrq1NIRFLUAQAAQAAAAHUAAABZAAAE" +
            "Ro4gAAAAAAABAAAAWgAAAwBgEAAAAAAAWBgABABwEAAAAAAAVVUAAGIQAAMyEBAAAQAAAGUAAAPyIBAA" +
            "AAAAAGgAAAICAAAAMQAACzIAEAAAAAAAAkAAAAAAAD8AAAA/AAAAAAAAAADmiiAAAAAAAAAAAABFAAAJ" +
            "8gAQAAEAAABGEBAAAQAAAEZ+EAAAAAAAAGAQAAAAAAAQAAAKQgAQAAAAAABGAhAAAQAAAAJAAADQs1k+" +
            "WRc3P5jdkz0AAAAANwAACdIAEAAAAAAABgAQAAAAAACmChAAAAAAAAYJEAABAAAANiAABYIgEAAAAAAA" +
            "OgAQAAEAAAAAAAAK0gAQAAAAAAAGDhAAAAAAAAJAAAAAAAC/AAAAAAAAAL8AAAC/MgAAC9IAEAAAAAAA" +
            "Bg4QAAAAAABWhSAAAAAAAAAAAAAGgCAAAAAAAAAAAAAAAAAK0gAQAAAAAAAGDhAAAAAAAAJAAAAAAAA/" +
            "AAAAAAAAAD8AAAA/AAAAC3IAEAABAAAAhgMQgEEAAAAAAAAAAkAAAAAAgD8AAIA/AACAPwAAAAA3IAAJ" +
            "ciAQAAAAAABWBRAAAAAAAEYCEAABAAAAhgMQAAAAAAA+AAABU1RBVHQAAAALAAAAAgAAAAAAAAACAAAA" +
            "BgAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AQAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=="
        );

        /// <summary>
        /// Separable 9-Tap Gaussian Blur Pixel Shader
        /// </summary>
        public static byte[] PsGaussianBlurBytecode { get; } = Convert.FromBase64String(
            "RFhCQyBxORW+Em7yFIenEAnzaUwBAAAAGAcAAAUAAAA0AAAAfAEAANQBAAAIAgAAnAYAAFJERUZAAQAA" +
            "AQAAAKQAAAADAAAAHAAAAAAE//8AgQAAFgEAAHwAAAADAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAABAAAA" +
            "iwAAAAIAAAAFAAAABAAAAP////8AAAAAAQAAAA0AAACYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAA" +
            "AQAAAGRlZmF1bHRTYW1wbGVyAGlucHV0VGV4dHVyZQBCbHVyQnVmZmVyAKuYAAAAAgAAALwAAAAQAAAA" +
            "AAAAAAAAAADsAAAAAAAAAAgAAAACAAAA+AAAAAAAAAAIAQAACAAAAAgAAAACAAAA+AAAAAAAAABUZXhl" +
            "bFNpemUAq6sBAAMAAQACAAAAAAAAAAAAQmx1ckRpcmVjdGlvbgBNaWNyb3NvZnQgKFIpIEhMU0wgU2hh" +
            "ZGVyIENvbXBpbGVyIDEwLjEAq6tJU0dOUAAAAAIAAAAIAAAAOAAAAAAAAAABAAAAAwAAAAAAAAAPAAAA" +
            "RAAAAAAAAAAAAAAAAwAAAAEAAAADAwAAU1ZfUE9TSVRJT04AVEVYQ09PUkQAq6urT1NHTiwAAAABAAAA" +
            "CAAAACAAAAAAAAAAAAAAAAMAAAAAAAAADwAAAFNWX1RBUkdFVACrq1NIRFKMBAAAQAAAACMBAABZAAAE" +
            "Ro4gAAAAAAABAAAAWgAAAwBgEAAAAAAAWBgABABwEAAAAAAAVVUAAGIQAAMyEBAAAQAAAGUAAAPyIBAA" +
            "AAAAAGgAAAIEAAAAMgAACzIAEAAAAAAARoAgAAAAAAAAAAAA5oogAAAAAAAAAAAARhAQAAEAAABFAAAJ" +
            "8gAQAAAAAABGABAAAAAAAEZ+EAAAAAAAAGAQAAAAAAA4AAAK8gAQAAAAAABGDhAAAAAAAAJAAADPQ0c+" +
            "z0NHPs9DRz7PQ0c+RQAACfIAEAABAAAARhAQAAEAAABGfhAAAAAAAABgEAAAAAAAMgAADPIAEAAAAAAA" +
            "Rg4QAAEAAAACQAAAxHloPsR5aD7EeWg+xHloPkYOEAAAAAAAMgAADDIAEAABAAAARoAggEEAAAAAAAAA" +
            "AAAAAOaKIAAAAAAAAAAAAEYQEAABAAAARQAACfIAEAABAAAARgAQAAEAAABGfhAAAAAAAABgEAAAAAAA" +
            "MgAADPIAEAAAAAAARg4QAAEAAAACQAAAz0NHPs9DRz7PQ0c+z0NHPkYOEAAAAAAAOAAACfIAEAABAAAA" +
            "5o4gAAAAAAAAAAAARoQgAAAAAAAAAAAAMgAADDIAEAACAAAA5goQAAEAAAACQAAAAAAAQAAAAEAAAAAA" +
            "AAAAAEYQEAABAAAARQAACfIAEAACAAAARgAQAAIAAABGfhAAAAAAAABgEAAAAAAAMgAADPIAEAAAAAAA" +
            "Rg4QAAIAAAACQAAAvxT5Pb8U+T2/FPk9vxT5PUYOEAAAAAAAMgAADTIAEAACAAAA5goQgEEAAAABAAAA" +
            "AkAAAAAAAEAAAABAAAAAAAAAAABGEBAAAQAAAEUAAAnyABAAAgAAAEYAEAACAAAARn4QAAAAAAAAYBAA" +
            "AAAAADIAAAzyABAAAAAAAEYOEAACAAAAAkAAAL8U+T2/FPk9vxT5Pb8U+T1GDhAAAAAAADIAAAzyABAA" +
            "AgAAAEYOEAABAAAAAkAAAAAAQEAAAEBAAACAQAAAgEBGFBAAAQAAADIAAA3yABAAAQAAAEYOEIBBAAAA" +
            "AQAAAAJAAAAAAEBAAABAQAAAgEAAAIBARhQQAAEAAABFAAAJ8gAQAAMAAABGABAAAgAAAEZ+EAAAAAAA" +
            "AGAQAAAAAABFAAAJ8gAQAAIAAADmChAAAgAAAEZ+EAAAAAAAAGAQAAAAAAAyAAAM8gAQAAAAAABGDhAA" +
            "AwAAAAJAAAC6Z109umddPbpnXT26Z109Rg4QAAAAAABFAAAJ8gAQAAMAAABGABAAAQAAAEZ+EAAAAAAA" +
            "AGAQAAAAAABFAAAJ8gAQAAEAAADmChAAAQAAAEZ+EAAAAAAAAGAQAAAAAAAyAAAM8gAQAAAAAABGDhAA" +
            "AwAAAAJAAAC6Z109umddPbpnXT26Z109Rg4QAAAAAAAyAAAM8gAQAAAAAABGDhAAAgAAAAJAAABr14Q8" +
            "a9eEPGvXhDxr14Q8Rg4QAAAAAAAyAAAM8iAQAAAAAABGDhAAAQAAAAJAAABr14Q8a9eEPGvXhDxr14Q8" +
            "Rg4QAAAAAAA+AAABU1RBVHQAAAAaAAAABAAAAAAAAAACAAAAEAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAA=="
        );

        /// <summary>
        /// Sobel 3x3 Edge Detection Pixel Shader
        /// </summary>
        public static byte[] PsSobelBytecode { get; } = Convert.FromBase64String(
            "RFhCQ0HvfuqMRCZg3NAIv8sYrWUBAAAAPAkAAAUAAAA0AAAAtAEAAAwCAABAAgAAwAgAAFJERUZ4AQAA" +
            "AQAAAKQAAAADAAAAHAAAAAAE//8AgQAATwEAAHwAAAADAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAABAAAA" +
            "iwAAAAIAAAAFAAAABAAAAP////8AAAAAAQAAAA0AAACYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAA" +
            "AQAAAGRlZmF1bHRTYW1wbGVyAGlucHV0VGV4dHVyZQBTb2JlbEJ1ZmZlcgCYAAAAAwAAALwAAAAQAAAA" +
            "AAAAAAAAAAAEAQAAAAAAAAgAAAACAAAAFAEAAAAAAAAkAQAACAAAAAQAAAACAAAAMAEAAAAAAABAAQAA" +
            "DAAAAAQAAAACAAAAMAEAAAAAAABTb2JlbFRleGVsU2l6ZQCrAQADAAEAAgAAAAAAAAAAAE11bHRpcGxp" +
            "ZXIAqwAAAwABAAEAAAAAAAAAAABTb2JlbFRocmVzaG9sZABNaWNyb3NvZnQgKFIpIEhMU0wgU2hhZGVy" +
            "IENvbXBpbGVyIDEwLjEAq0lTR05QAAAAAgAAAAgAAAA4AAAAAAAAAAEAAAADAAAAAAAAAA8AAABEAAAA" +
            "AAAAAAAAAAADAAAAAQAAAAMDAABTVl9QT1NJVElPTgBURVhDT09SRACrq6tPU0dOLAAAAAEAAAAIAAAA" +
            "IAAAAAAAAAAAAAAAAwAAAAAAAAAPAAAAU1ZfVEFSR0VUAKurU0hEUngGAABAAAAAngEAAFkAAARGjiAA" +
            "AAAAAAEAAABaAAADAGAQAAAAAABYGAAEAHAQAAAAAABVVQAAYhAAAzIQEAABAAAAZQAAA/IgEAAAAAAA" +
            "aAAAAgMAAAA2AAAFQgAQAAAAAAABQAAAAAAAADYAAAeyABAAAAAAAEaEIIBBAAAAAAAAAAAAAAAAAAAH" +
            "8gAQAAAAAABGDhAAAAAAAEYUEAABAAAARQAACfIAEAABAAAARgAQAAAAAABGfhAAAAAAAABgEAAAAAAA" +
            "EAAAChIAEAAAAAAARgIQAAEAAAACQAAA0LNZPlkXNz+Y3ZM9AAAAAEUAAAnyABAAAQAAAOYKEAAAAAAA" +
            "Rn4QAAAAAAAAYBAAAAAAABAAAAoiABAAAAAAAEYCEAABAAAAAkAAANCzWT5ZFzc/mN2TPQAAAAAyAAAL" +
            "IgAQAAAAAAAaABCAQQAAAAAAAAABQAAAAAAAQAoAEIBBAAAAAAAAADIAAA3yABAAAQAAAEaEIAAAAAAA" +
            "AAAAAAJAAAAAAIA/AACAvwAAgL8AAIA/RhQQAAEAAABFAAAJ8gAQAAIAAABGABAAAQAAAEZ+EAAAAAAA" +
            "AGAQAAAAAABFAAAJ8gAQAAEAAADmChAAAQAAAEZ+EAAAAAAAAGAQAAAAAAAQAAAKQgAQAAAAAABGAhAA" +
            "AQAAAAJAAADQs1k+WRc3P5jdkz0AAAAAEAAACoIAEAAAAAAARgIQAAIAAAACQAAA0LNZPlkXNz+Y3ZM9" +
            "AAAAAAAAAAgiABAAAAAAADoAEIBBAAAAAAAAABoAEAAAAAAAAAAACBIAEAAAAAAAOgAQAAAAAAAKABCA" +
            "QQAAAAAAAAA2AAAFEgAQAAEAAAABQAAAAAAAADYAAAYiABAAAQAAABqAIAAAAAAAAAAAAAAAAAcyABAA" +
            "AQAAAEYAEAABAAAARhAQAAEAAABFAAAJ8gAQAAEAAABGABAAAQAAAEZ+EAAAAAAAAGAQAAAAAAAQAAAK" +
            "ggAQAAAAAABGAhAAAQAAAAJAAADQs1k+WRc3P5jdkz0AAAAAMgAACYIAEAAAAAAAOgAQAAAAAAABQAAA" +
            "AAAAQCoAEAAAAAAAAAAACDIAEAABAAAARhAQAAEAAABGgCAAAAAAAAAAAABFAAAJ8gAQAAEAAABGABAA" +
            "AQAAAEZ+EAAAAAAAAGAQAAAAAAAQAAAKEgAQAAEAAABGAhAAAQAAAAJAAADQs1k+WRc3P5jdkz0AAAAA" +
            "AAAAB4IAEAAAAAAAOgAQAAAAAAAKABAAAQAAAAAAAAhCABAAAAAAACoAEIBBAAAAAAAAAAoAEAABAAAA" +
            "AAAAByIAEAAAAAAAOgAQAAAAAAAaABAAAAAAADYAAAZCABAAAQAAAAqAIAAAAAAAAAAAADYAAAiiABAA" +
            "AQAAAAJAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB8IAEAABAAAApg4QAAEAAAAGFBAAAQAAAEUAAAnyABAA" +
            "AgAAAOYKEAABAAAARn4QAAAAAAAAYBAAAAAAABAAAAqCABAAAAAAAEYCEAACAAAAAkAAANCzWT5ZFzc/" +
            "mN2TPQAAAAAAAAAHggAQAAAAAAA6ABAAAAAAADoAEAAAAAAANgAABxIAEAABAAAACoAggEEAAAAAAAAA" +
            "AAAAAAAAAAcyABAAAQAAAEYAEAABAAAARhAQAAEAAABFAAAJ8gAQAAEAAABGABAAAQAAAEZ+EAAAAAAA" +
            "AGAQAAAAAAAQAAAKEgAQAAEAAABGAhAAAQAAAAJAAADQs1k+WRc3P5jdkz0AAAAAMgAACYIAEAAAAAAA" +
            "CgAQAAEAAAABQAAAAAAAwDoAEAAAAAAAAAAABxIAEAAAAAAAOgAQAAAAAAAKABAAAAAAAAAAAAcSABAA" +
            "AAAAACoAEAAAAAAACgAQAAAAAAAAAAAJEgAQAAAAAAAaABCAgQAAAAAAAAAKABCAgQAAAAAAAAA4AAAI" +
            "EgAQAAAAAAAKABAAAAAAACqAIAAAAAAAAAAAAB0AAAgiABAAAAAAAAoAEAAAAAAAOoAgAAAAAAAAAAAA" +
            "AQAAByIAEAAAAAAAGgAQAAAAAAABQAAAAACAPzEAAAhCABAAAAAAAAFAAAAAAAAAOoAgAAAAAAAAAAAA" +
            "NwAACRIAEAAAAAAAKgAQAAAAAAAaABAAAAAAAAoAEAAAAAAANiAABXIgEAAAAAAABgAQAAAAAAA2AAAF" +
            "giAQAAAAAAABQAAAAACAPz4AAAFTVEFUdAAAADEAAAADAAAAAAAAAAIAAAAfAAAAAAAAAAEAAAABAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAHAAAAAQAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        );

        /// <summary>
        /// Laplacian Sharpening Pixel Shader
        /// </summary>
        public static byte[] PsSharpenBytecode { get; } = Convert.FromBase64String(
            "RFhCQ5cgP1Gt355n+6ukotttcqUBAAAAzAUAAAUAAAA0AAAAwAEAABgCAABMAgAAUAUAAFJERUaEAQAA" +
            "AQAAAKgAAAADAAAAHAAAAAAE//8AgQAAWwEAAHwAAAADAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAABAAAA" +
            "iwAAAAIAAAAFAAAABAAAAP////8AAAAAAQAAAA0AAACYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAA" +
            "AQAAAGRlZmF1bHRTYW1wbGVyAGlucHV0VGV4dHVyZQBTaGFycGVuQnVmZmVyAKurmAAAAAMAAADAAAAA" +
            "EAAAAAAAAAAAAAAACAEAAAAAAAAIAAAAAgAAABwBAAAAAAAALAEAAAgAAAAEAAAAAgAAADwBAAAAAAAA" +
            "TAEAAAwAAAAEAAAAAAAAADwBAAAAAAAAU2hhcnBlblRleGVsU2l6ZQCrq6sBAAMAAQACAAAAAAAAAAAA" +
            "U2hhcnBlblN0cmVuZ3RoAAAAAwABAAEAAAAAAAAAAABTaGFycGVuUGFkZGluZwBNaWNyb3NvZnQgKFIp" +
            "IEhMU0wgU2hhZGVyIENvbXBpbGVyIDEwLjEAq0lTR05QAAAAAgAAAAgAAAA4AAAAAAAAAAEAAAADAAAA" +
            "AAAAAA8AAABEAAAAAAAAAAAAAAADAAAAAQAAAAMDAABTVl9QT1NJVElPTgBURVhDT09SRACrq6tPU0dO" +
            "LAAAAAEAAAAIAAAAIAAAAAAAAAAAAAAAAwAAAAAAAAAPAAAAU1ZfVEFSR0VUAKurU0hEUvwCAABAAAAA" +
            "vwAAAFkAAARGjiAAAAAAAAEAAABaAAADAGAQAAAAAABYGAAEAHAQAAAAAABVVQAAYhAAAzIQEAABAAAA" +
            "ZQAAA/IgEAAAAAAAaAAAAgMAAAA2AAAHIgAQAAAAAAAagCCAQQAAAAAAAAAAAAAANgAACFIAEAAAAAAA" +
            "AkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHMgAQAAAAAABGABAAAAAAAEYQEAABAAAARQAACfIAEAABAAAA" +
            "RgAQAAAAAABGfhAAAAAAAABgEAAAAAAANgAABoIAEAAAAAAAGoAgAAAAAAAAAAAAAAAABzIAEAAAAAAA" +
            "5goQAAAAAABGEBAAAQAAAEUAAAnyABAAAAAAAEYAEAAAAAAARn4QAAAAAAAAYBAAAAAAAAAAAAdyABAA" +
            "AAAAAEYCEAAAAAAARgIQAAEAAAA2AAAHEgAQAAEAAAAKgCCAQQAAAAAAAAAAAAAANgAACKIAEAABAAAA" +
            "AkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHMgAQAAEAAABGABAAAQAAAEYQEAABAAAARQAACfIAEAACAAAA" +
            "RgAQAAEAAABGfhAAAAAAAABgEAAAAAAAAAAAB3IAEAAAAAAARgIQAAAAAABGAhAAAgAAADYAAAZCABAA" +
            "AQAAAAqAIAAAAAAAAAAAAAAAAAcyABAAAQAAAOYKEAABAAAARhAQAAEAAABFAAAJ8gAQAAEAAABGABAA" +
            "AQAAAEZ+EAAAAAAAAGAQAAAAAAAAAAAHcgAQAAAAAABGAhAAAAAAAEYCEAABAAAAOAAACHIAEAAAAAAA" +
            "RgIQAAAAAACmiiAAAAAAAAAAAAAyAAAKggAQAAAAAAAqgCAAAAAAAAAAAAABQAAAAACAQAFAAAAAAIA/" +
            "RQAACfIAEAABAAAARhAQAAEAAABGfhAAAAAAAABgEAAAAAAAMiAACnIgEAAAAAAARgIQAAEAAAD2DxAA" +
            "AAAAAEYCEIBBAAAAAAAAADYgAAWCIBAAAAAAADoAEAABAAAAPgAAAVNUQVR0AAAAFwAAAAMAAAAAAAAA" +
            "AgAAAAwAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA="
        );

        /// <summary>
        /// Binary Thresholding Pixel Shader
        /// </summary>
        public static byte[] PsThresholdBytecode { get; } = Convert.FromBase64String(
            "RFhCQ0+WNlFQf7+5/qUGG+Rkrl0BAAAAJAQAAAUAAAA0AAAAuAEAABACAABEAgAAqAMAAFJERUZ8AQAA" +
            "AQAAAKgAAAADAAAAHAAAAAAE//8AgQAAVAEAAHwAAAADAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAABAAAA" +
            "iwAAAAIAAAAFAAAABAAAAP////8AAAAAAQAAAA0AAACYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAA" +
            "AQAAAGRlZmF1bHRTYW1wbGVyAGlucHV0VGV4dHVyZQBUaHJlc2hvbGRCdWZmZXIAmAAAAAMAAADAAAAA" +
            "EAAAAAAAAAAAAAAACAEAAAAAAAAEAAAAAgAAABABAAAAAAAAIAEAAAQAAAAEAAAAAgAAABABAAAAAAAA" +
            "MAEAAAgAAAAIAAAAAAAAAEQBAAAAAAAAQ3V0b2ZmAKsAAAMAAQABAAAAAAAAAAAAVGhyZXNob2xkSW52" +
            "ZXJ0AFRocmVzaG9sZFBhZGRpbmcAq6urAQADAAEAAgAAAAAAAAAAAE1pY3Jvc29mdCAoUikgSExTTCBT" +
            "aGFkZXIgQ29tcGlsZXIgMTAuMQBJU0dOUAAAAAIAAAAIAAAAOAAAAAAAAAABAAAAAwAAAAAAAAAPAAAA" +
            "RAAAAAAAAAAAAAAAAwAAAAEAAAADAwAAU1ZfUE9TSVRJT04AVEVYQ09PUkQAq6urT1NHTiwAAAABAAAA" +
            "CAAAACAAAAAAAAAAAAAAAAMAAAAAAAAADwAAAFNWX1RBUkdFVACrq1NIRFJcAQAAQAAAAFcAAABZAAAE" +
            "Ro4gAAAAAAABAAAAWgAAAwBgEAAAAAAAWBgABABwEAAAAAAAVVUAAGIQAAMyEBAAAQAAAGUAAAPyIBAA" +
            "AAAAAGgAAAIBAAAARQAACfIAEAAAAAAARhAQAAEAAABGfhAAAAAAAABgEAAAAAAAEAAAChIAEAAAAAAA" +
            "RgIQAAAAAAACQAAA0LNZPlkXNz+Y3ZM9AAAAAB0AAAgSABAAAAAAAAoAEAAAAAAACoAgAAAAAAAAAAAA" +
            "AQAAByIAEAAAAAAACgAQAAAAAAABQAAAAACAPzcAAAkSABAAAAAAAAoAEAAAAAAAAUAAAAAAAAABQAAA" +
            "AACAPzEAAAhCABAAAAAAAAFAAAAAAAA/GoAgAAAAAAAAAAAANwAACXIgEAAAAAAApgoQAAAAAAAGABAA" +
            "AAAAAFYFEAAAAAAANgAABYIgEAAAAAAAAUAAAAAAgD8+AAABU1RBVHQAAAAJAAAAAQAAAAAAAAACAAAA" +
            "AwAAAAAAAAABAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AQAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=="
        );

        /// <summary>
        /// Multi-pass Fused Mega-kernel Pixel Shader
        /// </summary>
        public static byte[] PsFusedBytecode { get; } = Convert.FromBase64String(
            "RFhCQ8TvTzxiZfF4YjVkod1RpOIBAAAArAgAAAUAAAA0AAAAXAIAALQCAADoAgAAMAgAAFJERUYgAgAA" +
            "AQAAAKQAAAADAAAAHAAAAAAE//8AgQAA9wEAAHwAAAADAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAABAAAA" +
            "iwAAAAIAAAAFAAAABAAAAP////8AAAAAAQAAAA0AAACYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAA" +
            "AQAAAGRlZmF1bHRTYW1wbGVyAGlucHV0VGV4dHVyZQBGdXNlZEJ1ZmZlcgCYAAAABwAAALwAAAAgAAAA" +
            "AAAAAAAAAABkAQAAAAAAAAgAAAACAAAAdAEAAAAAAACEAQAACAAAAAQAAAACAAAAlAEAAAAAAACkAQAA" +
            "DAAAAAQAAAACAAAAlAEAAAAAAACyAQAAEAAAAAQAAAACAAAAlAEAAAAAAADBAQAAFAAAAAQAAAACAAAA" +
            "lAEAAAAAAADNAQAAGAAAAAQAAAACAAAAlAEAAAAAAADiAQAAHAAAAAQAAAACAAAAlAEAAAAAAABGdXNl" +
            "ZFRleGVsU2l6ZQCrAQADAAEAAgAAAAAAAAAAAEZ1c2VkQnJpZ2h0bmVzcwAAAAMAAQABAAAAAAAAAAAA" +
            "RnVzZWRDb250cmFzdABGdXNlZEdyYXlzY2FsZQBGdXNlZEludmVydABGdXNlZFNoYXJwZW5TdHJlbmd0" +
            "aABGdXNlZFRocmVzaG9sZEN1dG9mZgBNaWNyb3NvZnQgKFIpIEhMU0wgU2hhZGVyIENvbXBpbGVyIDEw" +
            "LjEAq0lTR05QAAAAAgAAAAgAAAA4AAAAAAAAAAEAAAADAAAAAAAAAA8AAABEAAAAAAAAAAAAAAADAAAA" +
            "AQAAAAMDAABTVl9QT1NJVElPTgBURVhDT09SRACrq6tPU0dOLAAAAAEAAAAIAAAAIAAAAAAAAAAAAAAA" +
            "AwAAAAAAAAAPAAAAU1ZfVEFSR0VUAKurU0hEUkAFAABAAAAAUAEAAFkAAARGjiAAAAAAAAIAAABaAAAD" +
            "AGAQAAAAAABYGAAEAHAQAAAAAABVVQAAYhAAAzIQEAABAAAAZQAAA/IgEAAAAAAAaAAAAgYAAAAxAAAL" +
            "cgAQAAAAAAACQAAAAAAAAAAAAD8AAAA/AAAAACaJIAAAAAAAAQAAAB8ABAMKABAAAAAAAEUAAAnyABAA" +
            "AQAAAEYQEAABAAAARn4QAAAAAAAAYBAAAAAAADYAAAhSABAAAgAAAAJAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "NgAAByIAEAACAAAAGoAggEEAAAAAAAAAAAAAAAAAAAeSABAAAAAAAAYEEAACAAAABhQQAAEAAABFAAAJ" +
            "8gAQAAMAAADGABAAAAAAAEZ+EAAAAAAAAGAQAAAAAAA2AAAGggAQAAIAAAAagCAAAAAAAAAAAAAAAAAH" +
            "kgAQAAAAAACmDhAAAgAAAAYUEAABAAAARQAACfIAEAACAAAAxgAQAAAAAABGfhAAAAAAAABgEAAAAAAA" +
            "NgAABxIAEAAEAAAACoAggEEAAAAAAAAAAAAAADYAAAiiABAABAAAAAJAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAB5IAEAAAAAAABgQQAAQAAAAGFBAAAQAAAEUAAAnyABAABQAAAMYAEAAAAAAARn4QAAAAAAAAYBAA" +
            "AAAAADYAAAZCABAABAAAAAqAIAAAAAAAAAAAAAAAAAeSABAAAAAAAKYOEAAEAAAABhQQAAEAAABFAAAJ" +
            "8gAQAAQAAADGABAAAAAAAEZ+EAAAAAAAAGAQAAAAAAAyAAAKEgAQAAAAAAAqgCAAAAAAAAEAAAABQAAA" +
            "AACAQAFAAAAAAIA/AAAAB3IAEAACAAAARgIQAAIAAABGAhAAAwAAAAAAAAdyABAAAgAAAEYCEAAFAAAA" +
            "RgIQAAIAAAAAAAAHcgAQAAIAAABGAhAABAAAAEYCEAACAAAAOAAACHIAEAACAAAARgIQAAIAAACmiiAA" +
            "AAAAAAEAAAAyAAAKcgAQAAEAAABGAhAAAQAAAAYAEAAAAAAARgIQgEEAAAACAAAAEgAAAUUAAAnyABAA" +
            "AQAAAEYQEAABAAAARn4QAAAAAAAAYBAAAAAAABUAAAEQAAAKEgAQAAAAAABGAhAAAQAAAAJAAADQs1k+" +
            "WRc3P5jdkz0AAAAANwAACbIAEAAAAAAAVgUQAAAAAAAGABAAAAAAAEYIEAABAAAAAAAACrIAEAAAAAAA" +
            "RgwQAAAAAAACQAAAAAAAvwAAAL8AAAAAAAAAvzIAAAuyABAAAAAAAEYMEAAAAAAA9o8gAAAAAAAAAAAA" +
            "poogAAAAAAAAAAAAAAAACrIAEAAAAAAARgwQAAAAAAACQAAAAAAAPwAAAD8AAAAAAAAAPwAAAAtyABAA" +
            "AgAAAEYDEIBBAAAAAAAAAAJAAAAAAIA/AACAPwAAgD8AAAAANwAACXIAEAABAAAApgoQAAAAAABGAhAA" +
            "AgAAAEYDEAAAAAAANiAABfIAEAABAAAARg4QAAEAAAAdAAAIEgAQAAAAAAA6gCAAAAAAAAEAAAABQAAA" +
            "AAAAABAAAAoiABAAAAAAAEYCEAABAAAAAkAAANCzWT5ZFzc/mN2TPQAAAAAdAAAIIgAQAAAAAAAaABAA" +
            "AAAAADqAIAAAAAAAAQAAAAEAAApyABAAAgAAAFYFEAAAAAAAAkAAAAAAgD8AAIA/AACAPwAAAAA2AAAF" +
            "ggAQAAIAAAABQAAAAACAPzcAAAnyIBAAAAAAAAYAEAAAAAAARg4QAAIAAABGDhAAAQAAAD4AAAFTVEFU" +
            "dAAAACkAAAAGAAAAAAAAAAIAAAAVAAAAAAAAAAEAAAACAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "BgAAAAAAAAAAAAAAAAAAAAAAAAAGAAAAAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        );

        /// <summary>
        /// Mathematical Morphology Dilation Pixel Shader
        /// </summary>
        public static byte[] PsDilateBytecode { get; } = Convert.FromBase64String(
            "RFhCQ1dLwCJLWvEFlG1hO2/keYkBAAAAAAUAAAUAAAA0AAAAzAEAACQCAABYAgAAhAQAAFJERUaQAQAA" +
            "AQAAAKwAAAADAAAAHAAAAAAE//8AgQAAaAEAAHwAAAADAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAABAAAA" +
            "iwAAAAIAAAAFAAAABAAAAP////8AAAAAAQAAAA0AAACYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAA" +
            "AQAAAGRlZmF1bHRTYW1wbGVyAGlucHV0VGV4dHVyZQBNb3JwaG9sb2d5QnVmZmVyAKurq5gAAAADAAAA" +
            "xAAAABAAAAAAAAAAAAAAAAwBAAAAAAAACAAAAAIAAAAcAQAAAAAAACwBAAAIAAAABAAAAAIAAAA4AQAA" +
            "AAAAAEgBAAAMAAAABAAAAAAAAABYAQAAAAAAAE1vcnBoVGV4ZWxTaXplAKsBAAMAAQACAAAAAAAAAAAA" +
            "TW9ycGhSYWRpdXMAAAACAAEAAQAAAAAAAAAAAE1vcnBoUGFkZGluZwCrq6sAAAMAAQABAAAAAAAAAAAA" +
            "TWljcm9zb2Z0IChSKSBITFNMIFNoYWRlciBDb21waWxlciAxMC4xAElTR05QAAAAAgAAAAgAAAA4AAAA" +
            "AAAAAAEAAAADAAAAAAAAAA8AAABEAAAAAAAAAAAAAAADAAAAAQAAAAMDAABTVl9QT1NJVElPTgBURVhD" +
            "T09SRACrq6tPU0dOLAAAAAEAAAAIAAAAIAAAAAAAAAAAAAAAAwAAAAAAAAAPAAAAU1ZfVEFSR0VUAKur" +
            "U0hEUiQCAABAAAAAiQAAAFkAAARGjiAAAAAAAAEAAABaAAADAGAQAAAAAABYGAAEAHAQAAAAAABVVQAA" +
            "YhAAAzIQEAABAAAAZQAAA/IgEAAAAAAAaAAAAgUAAAAoAAAGEgAQAAAAAAAqgCAAAAAAAAAAAAA2AAAI" +
            "8gAQAAEAAAACQAAAAAAAAAAAAAAAAAAAAAAAADYAAAUiABAAAAAAAAoAEAAAAAAAMAAAASIAAAhCABAA" +
            "AAAAACqAIAAAAAAAAAAAABoAEAAAAAAAAwAEAyoAEAAAAAAAKwAABSIAEAACAAAAGgAQAAAAAAA2AAAF" +
            "8gAQAAMAAABGDhAAAQAAADYAAAVCABAAAAAAAAoAEAAAAAAAMAAAASIAAAiCABAAAAAAACqAIAAAAAAA" +
            "AAAAACoAEAAAAAAAAwAEAzoAEAAAAAAAKwAABRIAEAACAAAAKgAQAAAAAAAyAAAKUgAQAAIAAAAGARAA" +
            "AgAAAAaBIAAAAAAAAAAAAAYREAABAAAARQAACfIAEAAEAAAAhgAQAAIAAABGfhAAAAAAAABgEAAAAAAA" +
            "NAAAB/IAEAADAAAARg4QAAMAAABGDhAABAAAAB4AAAdCABAAAAAAACoAEAAAAAAAAUAAAAEAAAAWAAAB" +
            "NgAABfIAEAABAAAARg4QAAMAAAAeAAAHIgAQAAAAAAAaABAAAAAAAAFAAAABAAAAFgAAATYAAAXyIBAA" +
            "AAAAAEYOEAABAAAAPgAAAVNUQVR0AAAAFwAAAAUAAAAAAAAAAgAAAAIAAAAFAAAAAAAAAAEAAAACAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAYAAAAAAAAAAgAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAA="
        );

        /// <summary>
        /// Mathematical Morphology Erosion Pixel Shader
        /// </summary>
        public static byte[] PsErodeBytecode { get; } = Convert.FromBase64String(
            "RFhCQxI2hLD3sPLTPriJOU5J0P4BAAAAAAUAAAUAAAA0AAAAzAEAACQCAABYAgAAhAQAAFJERUaQAQAA" +
            "AQAAAKwAAAADAAAAHAAAAAAE//8AgQAAaAEAAHwAAAADAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAABAAAA" +
            "iwAAAAIAAAAFAAAABAAAAP////8AAAAAAQAAAA0AAACYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAA" +
            "AQAAAGRlZmF1bHRTYW1wbGVyAGlucHV0VGV4dHVyZQBNb3JwaG9sb2d5QnVmZmVyAKurq5gAAAADAAAA" +
            "xAAAABAAAAAAAAAAAAAAAAwBAAAAAAAACAAAAAIAAAAcAQAAAAAAACwBAAAIAAAABAAAAAIAAAA4AQAA" +
            "AAAAAEgBAAAMAAAABAAAAAAAAABYAQAAAAAAAE1vcnBoVGV4ZWxTaXplAKsBAAMAAQACAAAAAAAAAAAA" +
            "TW9ycGhSYWRpdXMAAAACAAEAAQAAAAAAAAAAAE1vcnBoUGFkZGluZwCrq6sAAAMAAQABAAAAAAAAAAAA" +
            "TWljcm9zb2Z0IChSKSBITFNMIFNoYWRlciBDb21waWxlciAxMC4xAElTR05QAAAAAgAAAAgAAAA4AAAA" +
            "AAAAAAEAAAADAAAAAAAAAA8AAABEAAAAAAAAAAAAAAADAAAAAQAAAAMDAABTVl9QT1NJVElPTgBURVhD" +
            "T09SRACrq6tPU0dOLAAAAAEAAAAIAAAAIAAAAAAAAAAAAAAAAwAAAAAAAAAPAAAAU1ZfVEFSR0VUAKur" +
            "U0hEUiQCAABAAAAAiQAAAFkAAARGjiAAAAAAAAEAAABaAAADAGAQAAAAAABYGAAEAHAQAAAAAABVVQAA" +
            "YhAAAzIQEAABAAAAZQAAA/IgEAAAAAAAaAAAAgUAAAAoAAAGEgAQAAAAAAAqgCAAAAAAAAAAAAA2AAAI" +
            "8gAQAAEAAAACQAAAAACAPwAAgD8AAIA/AACAPzYAAAUiABAAAAAAAAoAEAAAAAAAMAAAASIAAAhCABAA" +
            "AAAAACqAIAAAAAAAAAAAABoAEAAAAAAAAwAEAyoAEAAAAAAAKwAABSIAEAACAAAAGgAQAAAAAAA2AAAF" +
            "8gAQAAMAAABGDhAAAQAAADYAAAVCABAAAAAAAAoAEAAAAAAAMAAAASIAAAiCABAAAAAAACqAIAAAAAAA" +
            "AAAAACoAEAAAAAAAAwAEAzoAEAAAAAAAKwAABRIAEAACAAAAKgAQAAAAAAAyAAAKUgAQAAIAAAAGARAA" +
            "AgAAAAaBIAAAAAAAAAAAAAYREAABAAAARQAACfIAEAAEAAAAhgAQAAIAAABGfhAAAAAAAABgEAAAAAAA" +
            "MwAAB/IAEAADAAAARg4QAAMAAABGDhAABAAAAB4AAAdCABAAAAAAACoAEAAAAAAAAUAAAAEAAAAWAAAB" +
            "NgAABfIAEAABAAAARg4QAAMAAAAeAAAHIgAQAAAAAAAaABAAAAAAAAFAAAABAAAAFgAAATYAAAXyIBAA" +
            "AAAAAEYOEAABAAAAPgAAAVNUQVR0AAAAFwAAAAUAAAAAAAAAAgAAAAIAAAAFAAAAAAAAAAEAAAACAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAYAAAAAAAAAAgAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAA="
        );

        /// <summary>
        /// 2D Affine Alignment Transformation Pixel Shader
        /// </summary>
        public static byte[] PsAffineTransformBytecode { get; } = Convert.FromBase64String(
            "RFhCQyNVUGRSi8rjP980EfIoVzcBAAAAWAYAAAUAAAA0AAAA2AIAADADAABkAwAA3AUAAFJERUacAgAA" +
            "AQAAAKgAAAADAAAAHAAAAAAE//8AgQAAdAIAAHwAAAADAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAABAAAA" +
            "iwAAAAIAAAAFAAAABAAAAP////8AAAAAAQAAAA0AAACYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAA" +
            "AQAAAGRlZmF1bHRTYW1wbGVyAGlucHV0VGV4dHVyZQBBZmZpbmVCdWZmZXIAq6urmAAAAAkAAADAAAAA" +
            "QAAAAAAAAAAAAAAAmAEAAAAAAAAIAAAAAgAAAKgBAAAAAAAAuAEAAAgAAAAIAAAAAgAAAKgBAAAAAAAA" +
            "ygEAABAAAAAEAAAAAgAAANwBAAAAAAAA7AEAABQAAAAEAAAAAgAAANwBAAAAAAAA+wEAABgAAAAEAAAA" +
            "AgAAANwBAAAAAAAACwIAABwAAAAEAAAAAgAAANwBAAAAAAAAGwIAACAAAAAQAAAAAgAAADACAAAAAAAA" +
            "QAIAADAAAAAEAAAAAgAAANwBAAAAAAAAVAIAADQAAAAMAAAAAAAAAGQCAAAAAAAAQWZmaW5lQ2VudGVy" +
            "AKurqwEAAwABAAIAAAAAAAAAAABBZmZpbmVUcmFuc2xhdGlvbgBBZmZpbmVDb3NUaGV0YQCrq6sAAAMA" +
            "AQABAAAAAAAAAAAAQWZmaW5lU2luVGhldGEAQWZmaW5lSW52U2NhbGVYAEFmZmluZUludlNjYWxlWQBB" +
            "ZmZpbmVCb3JkZXJDb2xvcgCrq6sBAAMAAQAEAAAAAAAAAAAAQWZmaW5lQ2xhbXBUb0JvcmRlcgBBZmZp" +
            "bmVQYWRkaW5nAKurAQADAAEAAwAAAAAAAAAAAE1pY3Jvc29mdCAoUikgSExTTCBTaGFkZXIgQ29tcGls" +
            "ZXIgMTAuMQBJU0dOUAAAAAIAAAAIAAAAOAAAAAAAAAABAAAAAwAAAAAAAAAPAAAARAAAAAAAAAAAAAAA" +
            "AwAAAAEAAAADAwAAU1ZfUE9TSVRJT04AVEVYQ09PUkQAq6urT1NHTiwAAAABAAAACAAAACAAAAAAAAAA" +
            "AAAAAAMAAAAAAAAADwAAAFNWX1RBUkdFVACrq1NIRFJwAgAAQAAAAJwAAABZAAAERo4gAAAAAAAEAAAA" +
            "WgAAAwBgEAAAAAAAWBgABABwEAAAAAAAVVUAAGIQAAMyEBAAAQAAAGUAAAPyIBAAAAAAAGgAAAICAAAA" +
            "AAAACTIAEAAAAAAARhAQAAEAAABGgCCAQQAAAAAAAAAAAAAAAAAACTIAEAAAAAAARgAQAAAAAADmiiCA" +
            "QQAAAAAAAAAAAAAAOAAACEIAEAAAAAAAGgAQAAAAAAAagCAAAAAAAAEAAAAyAAALQgAQAAAAAAAKgCAA" +
            "AAAAAAEAAAAKABAAAAAAACoAEIBBAAAAAAAAAA8AAAgSABAAAAAAABaFIAAAAAAAAQAAAEYAEAAAAAAA" +
            "OAAACDIAEAABAAAAJgoQAAAAAADmiiAAAAAAAAEAAAAAAAAIMgAQAAAAAABGABAAAQAAAEaAIAAAAAAA" +
            "AAAAADEAAAhCABAAAAAAAAFAAAAAAAA/CoAgAAAAAAADAAAAHwAEAyoAEAAAAAAAMQAACsIAEAAAAAAA" +
            "BgQQAAAAAAACQAAAAAAAAAAAAAAAAAAAAAAAADEAAAoyABAAAQAAAAJAAAAAAIA/AACAPwAAAAAAAAAA" +
            "RgAQAAAAAAA8AAAHQgAQAAAAAAAqABAAAAAAAAoAEAABAAAAPAAAB0IAEAAAAAAAOgAQAAAAAAAqABAA" +
            "AAAAADwAAAdCABAAAAAAABoAEAABAAAAKgAQAAAAAAAfAAQDKgAQAAAAAAA2AAAG8iAQAAAAAABGjiAA" +
            "AAAAAAIAAAA+AAABFQAAARUAAAFFAAAJ8iAQAAAAAABGABAAAAAAAEZ+EAAAAAAAAGAQAAAAAAA+AAAB" +
            "U1RBVHQAAAAVAAAAAgAAAAAAAAACAAAACgAAAAAAAAADAAAAAgAAAAIAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAA=="
        );

        /// <summary>
        /// Canny Non-Maximum Suppression Edge Thinning Pixel Shader
        /// </summary>
        public static byte[] PsCannyNmsBytecode { get; } = Convert.FromBase64String(
            "RFhCQ1GG/WRlK9J7r3aFywSiVO4BAAAAgAsAAAUAAAA0AAAAuAEAABACAABEAgAABAsAAFJERUZ8AQAA" +
            "AQAAAKQAAAADAAAAHAAAAAAE//8AgQAAVAEAAHwAAAADAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAABAAAA" +
            "iwAAAAIAAAAFAAAABAAAAP////8AAAAAAQAAAA0AAACYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAA" +
            "AQAAAGRlZmF1bHRTYW1wbGVyAGlucHV0VGV4dHVyZQBDYW5ueUJ1ZmZlcgCYAAAAAwAAALwAAAAQAAAA" +
            "AAAAAAAAAAAEAQAAAAAAAAgAAAACAAAAFAEAAAAAAAAkAQAACAAAAAQAAAACAAAANAEAAAAAAABEAQAA" +
            "DAAAAAQAAAACAAAANAEAAAAAAABDYW5ueVRleGVsU2l6ZQCrAQADAAEAAgAAAAAAAAAAAENhbm55VGhy" +
            "ZXNob2xkAKsAAAMAAQABAAAAAAAAAAAAQ2FubnlNdWx0aXBsaWVyAE1pY3Jvc29mdCAoUikgSExTTCBT" +
            "aGFkZXIgQ29tcGlsZXIgMTAuMQBJU0dOUAAAAAIAAAAIAAAAOAAAAAAAAAABAAAAAwAAAAAAAAAPAAAA" +
            "RAAAAAAAAAAAAAAAAwAAAAEAAAADAwAAU1ZfUE9TSVRJT04AVEVYQ09PUkQAq6urT1NHTiwAAAABAAAA" +
            "CAAAACAAAAAAAAAAAAAAAAMAAAAAAAAADwAAAFNWX1RBUkdFVACrq1NIRFK4CAAAQAAAAC4CAABZAAAE" +
            "Ro4gAAAAAAABAAAAWgAAAwBgEAAAAAAAWBgABABwEAAAAAAAVVUAAGIQAAMyEBAAAQAAAGUAAAPyIBAA" +
            "AAAAAGgAAAIEAAAANgAAB7IAEAAAAAAARoQggEEAAAAAAAAAAAAAAAAAAAcyABAAAAAAAEYAEAAAAAAA" +
            "RhAQAAEAAABFAAAJ8gAQAAEAAABGABAAAAAAAEZ+EAAAAAAAAGAQAAAAAAAQAAAKEgAQAAAAAABGAhAA" +
            "AQAAAAJAAADQs1k+WRc3P5jdkz0AAAAANgAABUIAEAAAAAAAAUAAAAAAAAAAAAAHYgAQAAAAAACmCxAA" +
            "AAAAAAYREAABAAAARQAACfIAEAABAAAAlgUQAAAAAABGfhAAAAAAAABgEAAAAAAAEAAACiIAEAAAAAAA" +
            "RgIQAAEAAAACQAAA0LNZPlkXNz+Y3ZM9AAAAADIAAA3yABAAAQAAAEaEIAAAAAAAAAAAAAJAAAAAAIA/" +
            "AACAvwAAgL8AAIA/RhQQAAEAAABFAAAJ8gAQAAIAAABGABAAAQAAAEZ+EAAAAAAAAGAQAAAAAAAQAAAK" +
            "QgAQAAAAAABGAhAAAgAAAAJAAADQs1k+WRc3P5jdkz0AAAAANgAABxIAEAACAAAACoAggEEAAAAAAAAA" +
            "AAAAADYAAAiiABAAAgAAAAJAAAAAAAAAAAAAAAAAAAAAAAAAAAAABzIAEAABAAAARgAQAAIAAABGEBAA" +
            "AQAAAEUAAAnyABAAAwAAAEYAEAABAAAARn4QAAAAAAAAYBAAAAAAABAAAAqCABAAAAAAAEYCEAADAAAA" +
            "AkAAANCzWT5ZFzc/mN2TPQAAAAA2AAAGQgAQAAIAAAAKgCAAAAAAAAAAAAAAAAAHMgAQAAEAAADmChAA" +
            "AgAAAEYQEAABAAAARQAACfIAEAACAAAARgAQAAEAAABGfhAAAAAAAABgEAAAAAAAEAAAChIAEAABAAAA" +
            "RgIQAAIAAAACQAAA0LNZPlkXNz+Y3ZM9AAAAAEUAAAnyABAAAgAAAOYKEAABAAAARn4QAAAAAAAAYBAA" +
            "AAAAABAAAAoiABAAAQAAAEYCEAACAAAAAkAAANCzWT5ZFzc/mN2TPQAAAAA2AAAFEgAQAAIAAAABQAAA" +
            "AAAAADYAAAYiABAAAgAAABqAIAAAAAAAAAAAAAAAAAfCABAAAQAAAAYEEAACAAAABhQQAAEAAABFAAAJ" +
            "8gAQAAIAAADmChAAAQAAAEZ+EAAAAAAAAGAQAAAAAAAQAAAKQgAQAAEAAABGAhAAAgAAAAJAAADQs1k+" +
            "WRc3P5jdkz0AAAAAAAAACDIAEAACAAAARhAQAAEAAABGgCAAAAAAAAAAAABFAAAJ8gAQAAIAAABGABAA" +
            "AgAAAEZ+EAAAAAAAAGAQAAAAAAAQAAAKggAQAAEAAABGAhAAAgAAAAJAAADQs1k+WRc3P5jdkz0AAAAA" +
            "AAAACBIAEAACAAAAKgAQAAAAAAAKABCAQQAAAAAAAAAAAAAHIgAQAAIAAAAKABAAAQAAAAoAEAABAAAA" +
            "MgAACSIAEAACAAAAOgAQAAAAAAABQAAAAAAAwBoAEAACAAAAAAAABxIAEAACAAAAGgAQAAIAAAAKABAA" +
            "AgAAAAAAAAgiABAAAgAAADoAEAABAAAAGgAQgEEAAAABAAAAAAAABxIAEAACAAAAGgAQAAIAAAAKABAA" +
            "AgAAADIAAAsiABAAAgAAABoAEIBBAAAAAAAAAAFAAAAAAABACgAQgEEAAAAAAAAAAAAACCIAEAACAAAA" +
            "KgAQgEEAAAAAAAAAGgAQAAIAAAAyAAAJQgAQAAIAAAAqABAAAQAAAAFAAAAAAABAGgAQAAEAAAAAAAAH" +
            "QgAQAAIAAAA6ABAAAQAAACoAEAACAAAAAAAAByIAEAACAAAAKgAQAAIAAAAaABAAAgAAADgAAAdCABAA" +
            "AgAAABoAEAACAAAAGgAQAAIAAAAyAAAJQgAQAAIAAAAKABAAAgAAAAoAEAACAAAAKgAQAAIAAABLAAAF" +
            "QgAQAAIAAAAqABAAAgAAADgAAAhCABAAAgAAACoAEAACAAAAOoAgAAAAAAAAAAAAMQAACIIAEAACAAAA" +
            "KgAQAAIAAAAqgCAAAAAAAAAAAAAfAAQDOgAQAAIAAAA2AAAI8iAQAAAAAAACQAAAAAAAAAAAAAAAAAAA" +
            "AACAPz4AAAEVAAABOAAACIIAEAACAAAACgAQgIEAAAACAAAAAUAAAM0T1D4xAAAIggAQAAIAAAAaABCA" +
            "gQAAAAIAAAA6ABAAAgAAAB8ABAM6ABAAAgAAADYAAAYSABAAAwAAADoAEICBAAAAAAAAADYAAAYiABAA" +
            "AwAAAAoAEICBAAAAAQAAABIAAAE4AAAIggAQAAAAAAAaABCAgQAAAAIAAAABQAAAzRPUPjEAAAiCABAA" +
            "AAAAAAoAEICBAAAAAgAAADoAEAAAAAAAHwAEAzoAEAAAAAAANgAABhIAEAADAAAAGgAQgIEAAAAAAAAA" +
            "NgAABiIAEAADAAAAKgAQgIEAAAABAAAAEgAAATgAAAciABAAAAAAABoAEAACAAAACgAQAAIAAAAxAAAH" +
            "IgAQAAAAAAABQAAAAAAAABoAEAAAAAAAHwAEAxoAEAAAAAAANgAABhIAEAADAAAAKgAQgIEAAAAAAAAA" +
            "NgAABiIAEAADAAAAGgAQgIEAAAABAAAAEgAAATYAAAYSABAAAwAAAAoAEICBAAAAAAAAADYAAAYiABAA" +
            "AwAAADoAEICBAAAAAQAAABUAAAEVAAABFQAAATEAAAcyABAAAAAAAKYKEAACAAAARgAQAAMAAAA8AAAH" +
            "EgAQAAAAAAAaABAAAAAAAAoAEAAAAAAAHwAEAwoAEAAAAAAANgAACPIgEAAAAAAAAkAAAAAAAAAAAAAA" +
            "AAAAAAAAgD8+AAABFQAAATYgAAVyIBAAAAAAAKYKEAACAAAANgAABYIgEAAAAAAAAUAAAAAAgD8+AAAB" +
            "U1RBVHQAAABSAAAABAAAAAAAAAACAAAAKAAAAAAAAAABAAAABgAAAAUAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAACQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAA=="
        );

        /// <summary>
        /// Non-Linear Gamma Correction Pixel Shader
        /// </summary>
        public static byte[] PsGammaBytecode { get; } = Convert.FromBase64String(
            "RFhCQyg3RY5yPDBMV0Xm0oDt/60BAAAAnAMAAAUAAAA0AAAAjAEAAOQBAAAYAgAAIAMAAFJERUZQAQAA" +
            "AQAAAKQAAAADAAAAHAAAAAAE//8AgQAAKAEAAHwAAAADAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAABAAAA" +
            "iwAAAAIAAAAFAAAABAAAAP////8AAAAAAQAAAA0AAACYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAA" +
            "AQAAAGRlZmF1bHRTYW1wbGVyAGlucHV0VGV4dHVyZQBHYW1tYUJ1ZmZlcgCYAAAAAgAAALwAAAAQAAAA" +
            "AAAAAAAAAADsAAAAAAAAAAQAAAACAAAA+AAAAAAAAAAIAQAABAAAAAwAAAAAAAAAGAEAAAAAAABHYW1t" +
            "YVZhbHVlAKsAAAMAAQABAAAAAAAAAAAAR2FtbWFQYWRkaW5nAKurqwEAAwABAAMAAAAAAAAAAABNaWNy" +
            "b3NvZnQgKFIpIEhMU0wgU2hhZGVyIENvbXBpbGVyIDEwLjEASVNHTlAAAAACAAAACAAAADgAAAAAAAAA" +
            "AQAAAAMAAAAAAAAADwAAAEQAAAAAAAAAAAAAAAMAAAABAAAAAwMAAFNWX1BPU0lUSU9OAFRFWENPT1JE" +
            "AKurq09TR04sAAAAAQAAAAgAAAAgAAAAAAAAAAAAAAADAAAAAAAAAA8AAABTVl9UQVJHRVQAq6tTSERS" +
            "AAEAAEAAAABAAAAAWQAABEaOIAAAAAAAAQAAAFoAAAMAYBAAAAAAAFgYAAQAcBAAAAAAAFVVAABiEAAD" +
            "MhAQAAEAAABlAAAD8iAQAAAAAABoAAACAQAAAEUAAAnyABAAAAAAAEYQEAABAAAARn4QAAAAAAAAYBAA" +
            "AAAAADQAAApyABAAAAAAAEYCEAAAAAAAAkAAAKzFJzesxSc3rMUnNwAAAAA2IAAFgiAQAAAAAAA6ABAA" +
            "AAAAAC8AAAVyABAAAAAAAEYCEAAAAAAAOAAACHIAEAAAAAAARgIQAAAAAAAGgCAAAAAAAAAAAAAZIAAF" +
            "ciAQAAAAAABGAhAAAAAAAD4AAAFTVEFUdAAAAAcAAAABAAAAAAAAAAIAAAAEAAAAAAAAAAAAAAABAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        );

    }
}
